import {
  Platform,
  StyleSheet,
  type PressableStateCallbackType,
} from "react-native";
import { COLORS, FONTS } from "../../constants/theme";

type FocusablePressableState = PressableStateCallbackType & {
  focused?: boolean;
};

export const sharedComponentStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F4F6FA" },
  blocked: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
    gap: 8,
  },
  title: {
    fontSize: FONTS.sizes.lg,
    fontWeight: "800",
    color: COLORS.textPrimary,
  },
  sub: { color: "#5F6368", marginTop: 6, fontSize: 13, lineHeight: 18 },
  focusRing: {
    borderColor: COLORS.primary + "88",
    shadowColor: COLORS.primary,
    shadowOpacity: 0.2,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 0 },
    elevation: 1,
  },
  metric: {
    minWidth: 126,
    borderWidth: 1,
    borderColor: COLORS.gray100,
    borderRadius: 12,
    backgroundColor: "#FBFCFE",
    paddingVertical: 11,
    paddingHorizontal: 12,
  },
  metricInteractive: { borderColor: COLORS.primary + "33" },
  metricValue: {
    fontWeight: "800",
    color: COLORS.textPrimary,
    fontSize: 16,
    lineHeight: 20,
  },
  metricLabel: {
    fontSize: 11,
    color: "#5F6368",
    marginTop: 3,
    lineHeight: 14,
  },
  metricMini: {
    minWidth: 112,
    borderWidth: 1,
    borderColor: COLORS.gray100,
    borderRadius: 12,
    backgroundColor: "#FBFCFE",
    paddingVertical: 10,
    paddingHorizontal: 11,
  },
  metricMiniValue: {
    fontWeight: "800",
    color: COLORS.textPrimary,
    fontSize: 13,
    lineHeight: 17,
  },
  metricMiniLabel: {
    fontSize: 10,
    color: "#5F6368",
    marginTop: 3,
    lineHeight: 13,
  },
  kpiCard: {
    minWidth: Platform.OS === "web" ? 128 : 112,
    flex: 1,
    borderWidth: 1,
    borderColor: COLORS.gray100,
    borderRadius: 10,
    backgroundColor: "#FBFCFE",
    paddingVertical: 12,
    paddingHorizontal: 12,
  },
  kpiValue: {
    color: COLORS.textPrimary,
    fontWeight: "800",
    fontSize: 18,
  },
  kpiLabel: {
    marginTop: 2,
    color: COLORS.textSecondary,
    fontSize: 11,
    fontWeight: "600",
  },
  sampleBadge: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  sampleBadgeText: {
    fontSize: 10,
    fontWeight: "800",
  },
  sampleBadgeHigh: {
    borderColor: COLORS.success + "55",
    backgroundColor: COLORS.success + "12",
  },
  sampleBadgeHighText: {
    color: COLORS.success,
  },
  sampleBadgeMedium: {
    borderColor: COLORS.warning + "55",
    backgroundColor: COLORS.warning + "12",
  },
  sampleBadgeMediumText: {
    color: COLORS.warning,
  },
  sampleBadgeLow: {
    borderColor: COLORS.error + "55",
    backgroundColor: COLORS.error + "12",
  },
  sampleBadgeLowText: {
    color: COLORS.error,
  },
  tab: {
    borderWidth: 1,
    borderColor: COLORS.gray200,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    minHeight: 36,
    backgroundColor: COLORS.white,
  },
  tabActive: {
    borderColor: COLORS.primary,
    backgroundColor: COLORS.primary + "12",
  },
  tabText: { color: "#5F6368", fontWeight: "700", fontSize: 12 },
  tabTextActive: { color: COLORS.primary },
  miniTab: {
    borderWidth: 1,
    borderColor: COLORS.gray200,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 7,
    minHeight: 36,
    backgroundColor: COLORS.white,
  },
  miniTabActive: {
    borderColor: COLORS.primary,
    backgroundColor: COLORS.primary + "12",
  },
  miniTabText: { color: "#5F6368", fontWeight: "700", fontSize: 11 },
  miniTabTextActive: { color: COLORS.primary },
  chip: {
    borderWidth: 1,
    borderColor: COLORS.gray200,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 7,
    minHeight: 36,
    backgroundColor: COLORS.white,
  },
  chipActive: {
    borderColor: COLORS.primary,
    backgroundColor: COLORS.primary + "12",
  },
  chipText: { color: "#5F6368", fontWeight: "700", fontSize: 11 },
  chipTextActive: { color: COLORS.primary },
  action: {
    backgroundColor: COLORS.primary,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 9,
    minHeight: 40,
    justifyContent: "center",
  },
  actionSecondary: {
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.gray200,
  },
  actionText: {
    color: COLORS.white,
    fontWeight: "700",
    fontSize: 13,
    lineHeight: 17,
  },
  actionTextSecondary: {
    color: "#5F6368",
  },
  small: {
    borderWidth: 1,
    borderColor: COLORS.gray200,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 7,
    minHeight: 36,
    backgroundColor: COLORS.white,
  },
  smallDanger: { borderColor: "#efb0b0", backgroundColor: "#fff5f5" },
  smallText: { fontSize: 11, color: "#5F6368", fontWeight: "700" },
  smallTextDanger: { color: "#b52828" },
  statusBadge: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  statusBadgeText: { fontSize: 11, fontWeight: "800" },
  reasonTag: {
    borderWidth: 1,
    borderColor: COLORS.gray200,
    borderRadius: 999,
    backgroundColor: COLORS.white,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  reasonTagText: { color: "#5F6368", fontSize: 11, fontWeight: "700" },
  head: {
    flexDirection: "row",
    gap: 8,
    borderWidth: 1,
    borderColor: COLORS.gray100,
    borderRadius: 12,
    backgroundColor: "#F7F9FC",
    paddingHorizontal: 12,
    paddingVertical: 9,
    minHeight: 42,
  },
  headText: { flex: 1, fontSize: 11, fontWeight: "700", color: "#5F6368" },
  headBtn: { flex: 1 },
  headTextActive: { color: COLORS.primary },
  row: {
    flexDirection: "row",
    gap: 8,
    borderWidth: 1,
    borderColor: COLORS.gray100,
    borderRadius: 12,
    backgroundColor: "#FBFCFE",
    paddingHorizontal: 12,
    paddingVertical: 11,
    marginTop: 8,
    minHeight: 46,
  },
  rowCell: { flex: 1, fontSize: 11, color: "#5F6368" },
  rowCellPrimary: { color: COLORS.textPrimary, fontWeight: "700" },
  selected: {
    borderColor: COLORS.primary + "55",
    backgroundColor: COLORS.primary + "08",
  },
  pagination: {
    marginTop: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    borderTopWidth: 1,
    borderTopColor: COLORS.gray100,
    paddingTop: 12,
  },
  paginationText: { color: "#5F6368", fontSize: 11, fontWeight: "700" },
  chartWrap: {
    gap: 12,
    paddingTop: 2,
  },
  chartLegendRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 10,
  },
  chartLegendItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    maxWidth: 160,
  },
  chartLegendDot: {
    width: 10,
    height: 10,
    borderRadius: 999,
  },
  chartLegendText: {
    color: "#64748B",
    fontSize: 12,
    fontWeight: "600",
  },
  chartScrollContent: {
    flexGrow: 1,
    paddingTop: 2,
  },
  chartYAxis: {
    width: 42,
    height: 178,
    paddingRight: 8,
    paddingTop: 20,
    paddingBottom: 32,
    justifyContent: "space-between",
    alignItems: "flex-end",
  },
  chartTickLabel: {
    color: "#7C8798",
    fontSize: 10,
    fontWeight: "600",
  },
  chartPlot: {
    height: 178,
    borderLeftWidth: 1,
    borderBottomWidth: 1,
    borderColor: "#E2E8F0",
    paddingHorizontal: 8,
    position: "relative",
  },
  chartGrid: {
    position: "absolute",
    top: 20,
    right: 0,
    bottom: 32,
    left: 0,
    justifyContent: "space-between",
  },
  chartGridLine: {
    borderTopWidth: 1,
    borderStyle: Platform.OS === "web" ? "dashed" : "solid",
    borderColor: "#E2E8F0",
  },
  chartBarsRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 8,
    height: 178,
  },
  chartBarColumn: {
    width: 48,
    height: 178,
    alignItems: "center",
    justifyContent: "flex-end",
  },
  chartBarSlot: {
    height: 118,
    width: "100%",
    justifyContent: "flex-end",
    alignItems: "center",
  },
  chartLabel: {
    color: "#64748B",
    fontSize: 10,
    fontWeight: "700",
    height: 26,
    lineHeight: 13,
    marginTop: 6,
    textAlign: "center",
    width: "100%",
  },
  chartValue: {
    color: COLORS.textPrimary,
    fontSize: 10,
    fontWeight: "800",
    height: 18,
    textAlign: "center",
    width: "100%",
  },
  chartFill: {
    width: 24,
    borderTopLeftRadius: 5,
    borderTopRightRadius: 5,
    borderBottomLeftRadius: 2,
    borderBottomRightRadius: 2,
  },
});

export const focusStyle = (state: PressableStateCallbackType) =>
  (state as FocusablePressableState).focused
    ? sharedComponentStyles.focusRing
    : null;
