import { Platform, StyleSheet } from "react-native";
import { BORDER_RADIUS, COLORS, FONTS, SPACING } from "../../constants/theme";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F4F6FA" },
  content: {
    padding: Platform.OS === "web" ? SPACING.lg : SPACING.base,
    gap: Platform.OS === "web" ? SPACING.lg : SPACING.base,
    paddingBottom: SPACING.xl,
  },
  card: {
    backgroundColor: COLORS.white,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: COLORS.gray100,
    padding: Platform.OS === "web" ? SPACING.lg : SPACING.base,
  },
  healthKpiBlock: {
    marginTop: SPACING.base,
    borderWidth: 1,
    borderColor: COLORS.primary + "14",
    borderRadius: 12,
    backgroundColor: COLORS.primary + "05",
    paddingVertical: Platform.OS === "web" ? SPACING.base : SPACING.sm,
    paddingHorizontal: Platform.OS === "web" ? SPACING.base : SPACING.sm,
  },
  loading: {
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.gray100,
    borderRadius: 12,
    padding: 16,
    alignItems: "center",
  },
  topRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    justifyContent: "space-between",
    alignItems: "center",
  },
  wrapRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    alignItems: "center",
  },
  split: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: Platform.OS === "web" ? SPACING.lg : SPACING.sm,
    alignItems: "flex-start",
  },
  pane: {
    flex: 1,
    minWidth: Platform.OS === "web" ? 360 : 280,
    backgroundColor: COLORS.white,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: COLORS.gray100,
    padding: SPACING.base,
  },
  chartPane: {
    flex: 1,
    minWidth: Platform.OS === "web" ? 320 : 260,
    backgroundColor: COLORS.white,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.gray100,
    padding: SPACING.sm,
  },
  chartTitle: {
    color: COLORS.textPrimary,
    fontWeight: "800",
    fontSize: 13,
    marginBottom: 12,
  },
  detailPane: { flexGrow: 0, flexBasis: Platform.OS === "web" ? 420 : 360 },
  title: {
    fontSize: FONTS.sizes.lg,
    fontWeight: "800",
    color: COLORS.textPrimary,
  },
  big: {
    fontSize: FONTS.sizes.base,
    fontWeight: "800",
    color: COLORS.textPrimary,
  },
  sub: { color: "#5F6368", marginTop: 6, fontSize: 13, lineHeight: 18 },
  muted: { color: "#5F6368", fontSize: 12, lineHeight: 17 },
  section: {
    fontSize: FONTS.sizes.base,
    fontWeight: "800",
    color: COLORS.textPrimary,
    marginBottom: 12,
  },
  search: {
    minWidth: Platform.OS === "web" ? 340 : 280,
    borderWidth: 1,
    borderColor: COLORS.gray100,
    borderRadius: 12,
    backgroundColor: "#FBFCFE",
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: COLORS.textPrimary,
    fontSize: 14,
  },
  filterInput: {
    minWidth: 128,
    borderWidth: 1,
    borderColor: COLORS.gray200,
    borderRadius: 999,
    backgroundColor: COLORS.white,
    paddingHorizontal: 12,
    paddingVertical: 7,
    color: COLORS.textPrimary,
    fontSize: 12,
  },
  panelActionsRow: {
    marginTop: SPACING.sm,
  },
  entityHeader: {
    marginTop: 2,
    marginBottom: SPACING.xs,
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "space-between",
    gap: SPACING.xs,
  },
  entityHeaderText: {
    flex: 1,
    minWidth: 180,
  },
  entityName: {
    color: COLORS.textPrimary,
    fontWeight: "800",
    fontSize: FONTS.sizes.lg,
    lineHeight: 30,
  },
  entityMeta: {
    color: "#5F6368",
    marginTop: 2,
    fontSize: 13,
    fontWeight: "500",
  },
  entityHeaderAction: {
    minWidth: 170,
  },
  panelFormTitle: {
    color: COLORS.textPrimary,
    fontWeight: "800",
    fontSize: 14,
    marginBottom: 2,
  },
  panelTabsRow: {
    marginTop: SPACING.sm,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    alignItems: "center",
  },
  panelMetricsRow: {
    marginTop: SPACING.sm,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    alignItems: "center",
  },
  panelPrimaryActions: {
    marginTop: SPACING.xs,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    alignItems: "center",
  },
  panelActionBtn: {
    minWidth: 150,
    minHeight: 42,
    alignItems: "center",
    justifyContent: "center",
  },
  kpiGrid: {
    marginTop: SPACING.xs,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACING.xs,
  },
  auditLogItem: {
    marginTop: 10,
    borderWidth: 1,
    borderColor: COLORS.gray100,
    borderRadius: 12,
    backgroundColor: "#FBFCFE",
    padding: 12,
    flexDirection: "row",
    gap: 10,
    alignItems: "center",
  },
  automationItem: {
    marginTop: 10,
    borderWidth: 1,
    borderColor: COLORS.gray100,
    borderRadius: 12,
    backgroundColor: "#FBFCFE",
    padding: 12,
    flexDirection: "row",
    gap: 10,
    alignItems: "center",
  },
  automationHistoryItem: {
    marginTop: 8,
    borderWidth: 1,
    borderColor: COLORS.gray100,
    borderRadius: 12,
    backgroundColor: COLORS.white,
    padding: 12,
  },
  subtleActionText: { color: "#5F6368", fontSize: 12, fontWeight: "600" },
  disclaimerText: {
    color: "#5F6368",
    fontSize: 11,
    lineHeight: 16,
    marginTop: 8,
  },
  insightsRow: {
    marginTop: SPACING.sm,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACING.xs,
  },
  insightCard: {
    flex: 1,
    minWidth: Platform.OS === "web" ? 240 : 220,
    borderWidth: 1,
    borderColor: COLORS.primary + "22",
    borderRadius: 12,
    backgroundColor: COLORS.white,
    padding: Platform.OS === "web" ? SPACING.sm : SPACING.xs,
  },
  insightCardPressed: {
    opacity: 0.9,
    borderColor: COLORS.primary + "55",
  },
  insightLabel: {
    color: "#5F6368",
    fontSize: 11,
    fontWeight: "700",
  },
  insightHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  insightTitle: {
    marginTop: 4,
    color: COLORS.textPrimary,
    fontSize: 15,
    fontWeight: "800",
  },
  insightValue: {
    marginTop: 2,
    color: COLORS.primary,
    fontSize: 14,
    fontWeight: "800",
  },
  insightSubValue: {
    marginTop: 2,
    color: "#5F6368",
    fontSize: 11,
    fontWeight: "600",
  },
  insightMetaRow: {
    marginTop: 2,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  insightHint: {
    color: "#5F6368",
    fontSize: 11,
    fontWeight: "600",
  },
  insightHintRow: {
    marginTop: 6,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 6,
  },
  emptyPhysicalExamCallout: {
    marginTop: SPACING.sm,
    borderWidth: 1,
    borderColor: COLORS.warning + "44",
    backgroundColor: COLORS.warning + "12",
    borderRadius: 12,
    padding: SPACING.sm,
  },
  coverageRow: {
    marginTop: SPACING.xs,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: SPACING.xs,
  },
  coverageActionRow: {
    marginTop: SPACING.xs,
    borderTopWidth: 1,
    borderTopColor: COLORS.gray100,
    paddingTop: SPACING.xs,
  },
  coverageBadge: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  coverageBadgeText: {
    fontSize: 11,
    fontWeight: "800",
  },
  coverageHigh: {
    borderColor: COLORS.success + "55",
    backgroundColor: COLORS.success + "12",
  },
  coverageHighText: {
    color: COLORS.success,
  },
  coverageMedium: {
    borderColor: COLORS.warning + "55",
    backgroundColor: COLORS.warning + "12",
  },
  coverageMediumText: {
    color: COLORS.warning,
  },
  coverageLow: {
    borderColor: COLORS.error + "55",
    backgroundColor: COLORS.error + "12",
  },
  coverageLowText: {
    color: COLORS.error,
  },
  topListRow: {
    marginTop: 6,
    paddingVertical: 6,
    borderTopWidth: 1,
    borderTopColor: COLORS.gray100,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  topListLabelWrap: {
    flex: 1,
    gap: 2,
  },
  topListLabel: {
    color: "#5F6368",
    fontSize: 12,
    fontWeight: "600",
  },
  topListDetail: {
    color: "#5F6368",
    fontSize: 10,
    fontWeight: "600",
  },
  topListDetailRow: {
    marginTop: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  topListValue: {
    color: COLORS.textPrimary,
    fontSize: 12,
    fontWeight: "800",
  },
  sampleInfoBox: {
    marginTop: SPACING.xs,
    borderWidth: 1,
    borderColor: COLORS.gray100,
    borderRadius: BORDER_RADIUS.md,
    backgroundColor: COLORS.white,
    paddingVertical: SPACING.xs,
    paddingHorizontal: SPACING.sm,
  },
  sampleInfoText: {
    marginTop: 4,
    color: COLORS.textPrimary,
    fontSize: 11,
    fontWeight: "700",
  },
  sampleInfoMuted: {
    marginTop: 4,
    color: "#5F6368",
    fontSize: 11,
  },
  input: {
    marginTop: 8,
    borderWidth: 1,
    borderColor: COLORS.gray100,
    borderRadius: 12,
    backgroundColor: "#FBFCFE",
    paddingHorizontal: 12,
    paddingVertical: 11,
    color: COLORS.textPrimary,
    fontSize: 14,
    lineHeight: 18,
  },
  selected: {
    borderColor: COLORS.primary + "55",
    backgroundColor: COLORS.primary + "08",
  },
  item: {
    marginTop: 10,
    borderWidth: 1,
    borderColor: COLORS.gray100,
    borderRadius: 12,
    backgroundColor: "#FBFCFE",
    padding: 12,
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
  },
  line: {
    marginTop: 8,
    borderWidth: 1,
    borderColor: COLORS.gray100,
    borderRadius: 12,
    backgroundColor: "#FBFCFE",
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  lineTitle: {
    color: COLORS.textPrimary,
    fontWeight: "700",
    fontSize: 13,
    lineHeight: 18,
  },
  lineSub: {
    color: "#5F6368",
    fontSize: 12,
    lineHeight: 17,
    marginTop: 3,
  },
  kanbanWrap: { flexDirection: "row", flexWrap: "wrap", gap: 12 },
  kanbanCol: {
    flex: 1,
    minWidth: 240,
    borderWidth: 1,
    borderColor: COLORS.gray100,
    borderRadius: 12,
    backgroundColor: "#F8FAFD",
    padding: 12,
  },
  kanbanCard: {
    marginTop: 10,
    borderWidth: 1,
    borderColor: COLORS.gray100,
    borderRadius: 12,
    backgroundColor: COLORS.white,
    padding: 12,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(17, 24, 39, 0.45)",
    alignItems: "center",
    justifyContent: "center",
    padding: SPACING.base,
  },
  modalCard: {
    width: "100%",
    maxWidth: 760,
    maxHeight: "88%",
    backgroundColor: COLORS.white,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: COLORS.gray100,
    padding: Platform.OS === "web" ? SPACING.lg : SPACING.base,
  },
  modalActionsGrid: {
    marginTop: SPACING.base,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
});
