export enum ExerciseImageType {
  MOBILIDADE_GERAL = 'MOBILIDADE_GERAL',
  MOBILIDADE_LOMBAR = 'MOBILIDADE_LOMBAR',
  CONTROLE_CERVICAL = 'CONTROLE_CERVICAL',
  OMBRO_MANGUITO = 'OMBRO_MANGUITO',
  JOELHO_AGACHAMENTO = 'JOELHO_AGACHAMENTO',
  QUADRIL_GLUTEOS = 'QUADRIL_GLUTEOS',
  TORNOZELO_EQUILIBRIO = 'TORNOZELO_EQUILIBRIO',
  PUNHO_PREENSAO = 'PUNHO_PREENSAO',
}

export const EXERCISE_IMAGE_TYPES = Object.values(ExerciseImageType);
