import { ExercicioStatus } from './entities/exercicio.entity';

export type MasterExerciseSeed = {
  nome: string;
  slug: string;
  regiaoCorporal: string;
  categoria: string;
  nivel: string;
  objetivo: string;
  descricao: string;
  instrucoesPadrao: string;
  cuidados: string;
  contraindicacoes: string;
  imagemKey: null;
  tags: string[];
  status: ExercicioStatus;
};

export type MasterExerciseTemplate = {
  nome: string;
  slug: string;
  area: string;
  regiaoCorporal: string;
  categoria: string;
  nivel: string;
  tags: string[];
};

export const MASTER_EXERCISE_TEMPLATES: MasterExerciseTemplate[] = [
  {
    nome: 'Retracao cervical em pe na parede',
    slug: 'retracao-cervical-em-pe-na-parede',
    area: 'Cervical / ATM',
    regiaoCorporal: 'CERVICAL_ATM',
    categoria: 'CONTROLE_MOTOR',
    nivel: 'INICIANTE',
    tags: [
      'cervical',
      'atm',
      'cervical_atm',
      'controle_motor',
      'retracao',
      'parede',
    ],
  },
  {
    nome: 'Retracao cervical em decubito com toalha',
    slug: 'retracao-cervical-em-decubito-com-toalha',
    area: 'Cervical / ATM',
    regiaoCorporal: 'CERVICAL_ATM',
    categoria: 'CONTROLE_MOTOR',
    nivel: 'INICIANTE',
    tags: [
      'cervical',
      'atm',
      'cervical_atm',
      'controle_motor',
      'retracao',
      'decubito',
      'com',
      'toalha',
    ],
  },
  {
    nome: 'Flexao cervical ativa curta',
    slug: 'flexao-cervical-ativa-curta',
    area: 'Cervical / ATM',
    regiaoCorporal: 'CERVICAL_ATM',
    categoria: 'MOBILIDADE',
    nivel: 'INICIANTE',
    tags: [
      'cervical',
      'atm',
      'cervical_atm',
      'mobilidade',
      'flexao',
      'ativa',
      'curta',
    ],
  },
  {
    nome: 'Rotacao cervical em decubito dorsal',
    slug: 'rotacao-cervical-em-decubito-dorsal',
    area: 'Cervical / ATM',
    regiaoCorporal: 'CERVICAL_ATM',
    categoria: 'MOBILIDADE',
    nivel: 'INICIANTE',
    tags: [
      'cervical',
      'atm',
      'cervical_atm',
      'mobilidade',
      'rotacao',
      'decubito',
      'dorsal',
    ],
  },
  {
    nome: 'Inclinacao cervical sem apoio manual',
    slug: 'inclinacao-cervical-sem-apoio-manual',
    area: 'Cervical / ATM',
    regiaoCorporal: 'CERVICAL_ATM',
    categoria: 'MOBILIDADE',
    nivel: 'INICIANTE',
    tags: [
      'cervical',
      'atm',
      'cervical_atm',
      'mobilidade',
      'inclinacao',
      'sem',
      'apoio',
      'manual',
    ],
  },
  {
    nome: 'Isometria cervical em flexao com mao',
    slug: 'isometria-cervical-em-flexao-com-mao',
    area: 'Cervical / ATM',
    regiaoCorporal: 'CERVICAL_ATM',
    categoria: 'FORTALECIMENTO',
    nivel: 'INICIANTE',
    tags: [
      'cervical',
      'atm',
      'cervical_atm',
      'fortalecimento',
      'isometria',
      'flexao',
      'com',
      'mao',
    ],
  },
  {
    nome: 'Isometria cervical em extensao na parede',
    slug: 'isometria-cervical-em-extensao-na-parede',
    area: 'Cervical / ATM',
    regiaoCorporal: 'CERVICAL_ATM',
    categoria: 'FORTALECIMENTO',
    nivel: 'INICIANTE',
    tags: [
      'cervical',
      'atm',
      'cervical_atm',
      'fortalecimento',
      'isometria',
      'extensao',
      'parede',
    ],
  },
  {
    nome: 'Isometria cervical lateral bilateral',
    slug: 'isometria-cervical-lateral-bilateral',
    area: 'Cervical / ATM',
    regiaoCorporal: 'CERVICAL_ATM',
    categoria: 'FORTALECIMENTO',
    nivel: 'INICIANTE',
    tags: [
      'cervical',
      'atm',
      'cervical_atm',
      'fortalecimento',
      'isometria',
      'lateral',
      'bilateral',
    ],
  },
  {
    nome: 'Deslizamento cervical com toalha',
    slug: 'deslizamento-cervical-com-toalha',
    area: 'Cervical / ATM',
    regiaoCorporal: 'CERVICAL_ATM',
    categoria: 'MOBILIDADE',
    nivel: 'INICIANTE',
    tags: [
      'cervical',
      'atm',
      'cervical_atm',
      'mobilidade',
      'deslizamento',
      'com',
      'toalha',
    ],
  },
  {
    nome: 'Alongamento elevador da escapula sentado',
    slug: 'alongamento-elevador-da-escapula-sentado',
    area: 'Cervical / ATM',
    regiaoCorporal: 'CERVICAL_ATM',
    categoria: 'MOBILIDADE',
    nivel: 'INICIANTE',
    tags: [
      'cervical',
      'atm',
      'cervical_atm',
      'mobilidade',
      'alongamento',
      'elevador',
      'escapula',
      'sentado',
    ],
  },
  {
    nome: 'Mobilidade suboccipital com toalha',
    slug: 'mobilidade-suboccipital-com-toalha',
    area: 'Cervical / ATM',
    regiaoCorporal: 'CERVICAL_ATM',
    categoria: 'MOBILIDADE',
    nivel: 'INICIANTE',
    tags: [
      'cervical',
      'atm',
      'cervical_atm',
      'mobilidade',
      'suboccipital',
      'com',
      'toalha',
    ],
  },
  {
    nome: 'Controle ocular cervical sentado',
    slug: 'controle-ocular-cervical-sentado',
    area: 'Cervical / ATM',
    regiaoCorporal: 'CERVICAL_ATM',
    categoria: 'CONTROLE_MOTOR',
    nivel: 'INICIANTE',
    tags: [
      'cervical',
      'atm',
      'cervical_atm',
      'controle_motor',
      'controle',
      'ocular',
      'sentado',
    ],
  },
  {
    nome: 'Protracao e retracao cervical sentada',
    slug: 'protracao-e-retracao-cervical-sentada',
    area: 'Cervical / ATM',
    regiaoCorporal: 'CERVICAL_ATM',
    categoria: 'CONTROLE_MOTOR',
    nivel: 'INICIANTE',
    tags: [
      'cervical',
      'atm',
      'cervical_atm',
      'controle_motor',
      'protracao',
      'retracao',
      'sentada',
    ],
  },
  {
    nome: 'Abertura mandibular controlada',
    slug: 'abertura-mandibular-controlada',
    area: 'Cervical / ATM',
    regiaoCorporal: 'CERVICAL_ATM',
    categoria: 'MOBILIDADE',
    nivel: 'INICIANTE',
    tags: [
      'cervical',
      'atm',
      'cervical_atm',
      'mobilidade',
      'abertura',
      'mandibular',
      'controlada',
    ],
  },
  {
    nome: 'Desvio lateral mandibular controlado',
    slug: 'desvio-lateral-mandibular-controlado',
    area: 'Cervical / ATM',
    regiaoCorporal: 'CERVICAL_ATM',
    categoria: 'MOBILIDADE',
    nivel: 'INICIANTE',
    tags: [
      'cervical',
      'atm',
      'cervical_atm',
      'mobilidade',
      'desvio',
      'lateral',
      'mandibular',
      'controlado',
    ],
  },
  {
    nome: 'Protrusao mandibular suave',
    slug: 'protrusao-mandibular-suave',
    area: 'Cervical / ATM',
    regiaoCorporal: 'CERVICAL_ATM',
    categoria: 'MOBILIDADE',
    nivel: 'INICIANTE',
    tags: [
      'cervical',
      'atm',
      'cervical_atm',
      'mobilidade',
      'protrusao',
      'mandibular',
      'suave',
    ],
  },
  {
    nome: 'Relaxamento mandibular com abertura parcial',
    slug: 'relaxamento-mandibular-com-abertura-parcial',
    area: 'Cervical / ATM',
    regiaoCorporal: 'CERVICAL_ATM',
    categoria: 'CONTROLE_MOTOR',
    nivel: 'INICIANTE',
    tags: [
      'cervical',
      'atm',
      'cervical_atm',
      'controle_motor',
      'relaxamento',
      'mandibular',
      'com',
      'abertura',
      'parcial',
    ],
  },
  {
    nome: 'Isometria mandibular em abertura',
    slug: 'isometria-mandibular-em-abertura',
    area: 'Cervical / ATM',
    regiaoCorporal: 'CERVICAL_ATM',
    categoria: 'FORTALECIMENTO',
    nivel: 'INICIANTE',
    tags: [
      'cervical',
      'atm',
      'cervical_atm',
      'fortalecimento',
      'isometria',
      'mandibular',
      'abertura',
    ],
  },
  {
    nome: 'Isometria mandibular lateral',
    slug: 'isometria-mandibular-lateral',
    area: 'Cervical / ATM',
    regiaoCorporal: 'CERVICAL_ATM',
    categoria: 'FORTALECIMENTO',
    nivel: 'INICIANTE',
    tags: [
      'cervical',
      'atm',
      'cervical_atm',
      'fortalecimento',
      'isometria',
      'mandibular',
      'lateral',
    ],
  },
  {
    nome: 'Mobilidade cervical em quatro apoios',
    slug: 'mobilidade-cervical-em-quatro-apoios',
    area: 'Cervical / ATM',
    regiaoCorporal: 'CERVICAL_ATM',
    categoria: 'MOBILIDADE',
    nivel: 'INICIANTE',
    tags: ['cervical', 'atm', 'cervical_atm', 'mobilidade', 'quatro', 'apoios'],
  },
  {
    nome: 'Extensao toracica no rolo',
    slug: 'extensao-toracica-no-rolo',
    area: 'Toracica / lombar / core',
    regiaoCorporal: 'TORACICA_LOMBAR_CORE',
    categoria: 'MOBILIDADE',
    nivel: 'INICIANTE',
    tags: [
      'toracica',
      'lombar',
      'core',
      'toracica_lombar_core',
      'mobilidade',
      'extensao',
      'rolo',
    ],
  },
  {
    nome: 'Rotacao toracica livro aberto',
    slug: 'rotacao-toracica-livro-aberto',
    area: 'Toracica / lombar / core',
    regiaoCorporal: 'TORACICA_LOMBAR_CORE',
    categoria: 'MOBILIDADE',
    nivel: 'INICIANTE',
    tags: [
      'toracica',
      'lombar',
      'core',
      'toracica_lombar_core',
      'mobilidade',
      'rotacao',
      'livro',
      'aberto',
    ],
  },
  {
    nome: 'Rotacao toracica em pe com bastao',
    slug: 'rotacao-toracica-em-pe-com-bastao',
    area: 'Toracica / lombar / core',
    regiaoCorporal: 'TORACICA_LOMBAR_CORE',
    categoria: 'MOBILIDADE',
    nivel: 'INICIANTE',
    tags: [
      'toracica',
      'lombar',
      'core',
      'toracica_lombar_core',
      'mobilidade',
      'rotacao',
      'com',
      'bastao',
    ],
  },
  {
    nome: 'Mobilidade toracica em decubito lateral',
    slug: 'mobilidade-toracica-em-decubito-lateral',
    area: 'Toracica / lombar / core',
    regiaoCorporal: 'TORACICA_LOMBAR_CORE',
    categoria: 'MOBILIDADE',
    nivel: 'INICIANTE',
    tags: [
      'toracica',
      'lombar',
      'core',
      'toracica_lombar_core',
      'mobilidade',
      'decubito',
      'lateral',
    ],
  },
  {
    nome: 'Alongamento latissimo com apoio na mesa',
    slug: 'alongamento-latissimo-com-apoio-na-mesa',
    area: 'Toracica / lombar / core',
    regiaoCorporal: 'TORACICA_LOMBAR_CORE',
    categoria: 'MOBILIDADE',
    nivel: 'INICIANTE',
    tags: [
      'toracica',
      'lombar',
      'core',
      'toracica_lombar_core',
      'mobilidade',
      'alongamento',
      'latissimo',
      'com',
      'apoio',
      'mesa',
    ],
  },
  {
    nome: 'Respiracao costal lateral',
    slug: 'respiracao-costal-lateral',
    area: 'Toracica / lombar / core',
    regiaoCorporal: 'TORACICA_LOMBAR_CORE',
    categoria: 'CONTROLE_MOTOR',
    nivel: 'INICIANTE',
    tags: [
      'toracica',
      'lombar',
      'core',
      'toracica_lombar_core',
      'controle_motor',
      'respiracao',
      'costal',
      'lateral',
    ],
  },
  {
    nome: 'Bascula pelvica sentada',
    slug: 'bascula-pelvica-sentada',
    area: 'Toracica / lombar / core',
    regiaoCorporal: 'TORACICA_LOMBAR_CORE',
    categoria: 'CONTROLE_MOTOR',
    nivel: 'INICIANTE',
    tags: [
      'toracica',
      'lombar',
      'core',
      'toracica_lombar_core',
      'controle_motor',
      'bascula',
      'pelvica',
      'sentada',
    ],
  },
  {
    nome: 'Bascula pelvica em quatro apoios',
    slug: 'bascula-pelvica-em-quatro-apoios',
    area: 'Toracica / lombar / core',
    regiaoCorporal: 'TORACICA_LOMBAR_CORE',
    categoria: 'CONTROLE_MOTOR',
    nivel: 'INICIANTE',
    tags: [
      'toracica',
      'lombar',
      'core',
      'toracica_lombar_core',
      'controle_motor',
      'bascula',
      'pelvica',
      'quatro',
      'apoios',
    ],
  },
  {
    nome: 'Ponte unilateral assistida',
    slug: 'ponte-unilateral-assistida',
    area: 'Toracica / lombar / core',
    regiaoCorporal: 'TORACICA_LOMBAR_CORE',
    categoria: 'FORTALECIMENTO',
    nivel: 'INICIANTE',
    tags: [
      'toracica',
      'lombar',
      'core',
      'toracica_lombar_core',
      'fortalecimento',
      'ponte',
      'unilateral',
      'assistida',
    ],
  },
  {
    nome: 'Ponte com aducao de bola',
    slug: 'ponte-com-aducao-de-bola',
    area: 'Toracica / lombar / core',
    regiaoCorporal: 'TORACICA_LOMBAR_CORE',
    categoria: 'FORTALECIMENTO',
    nivel: 'INICIANTE',
    tags: [
      'toracica',
      'lombar',
      'core',
      'toracica_lombar_core',
      'fortalecimento',
      'ponte',
      'com',
      'aducao',
      'bola',
    ],
  },
  {
    nome: 'Ponte com abducao de faixa',
    slug: 'ponte-com-abducao-de-faixa',
    area: 'Toracica / lombar / core',
    regiaoCorporal: 'TORACICA_LOMBAR_CORE',
    categoria: 'FORTALECIMENTO',
    nivel: 'INICIANTE',
    tags: [
      'toracica',
      'lombar',
      'core',
      'toracica_lombar_core',
      'fortalecimento',
      'ponte',
      'com',
      'abducao',
      'faixa',
    ],
  },
  {
    nome: 'Dead bug toque de calcanhar',
    slug: 'dead-bug-toque-de-calcanhar',
    area: 'Toracica / lombar / core',
    regiaoCorporal: 'TORACICA_LOMBAR_CORE',
    categoria: 'CONTROLE_MOTOR',
    nivel: 'INICIANTE',
    tags: [
      'toracica',
      'lombar',
      'core',
      'toracica_lombar_core',
      'controle_motor',
      'dead',
      'bug',
      'toque',
      'calcanhar',
    ],
  },
  {
    nome: 'Dead bug bracos alternados',
    slug: 'dead-bug-bracos-alternados',
    area: 'Toracica / lombar / core',
    regiaoCorporal: 'TORACICA_LOMBAR_CORE',
    categoria: 'CONTROLE_MOTOR',
    nivel: 'INICIANTE',
    tags: [
      'toracica',
      'lombar',
      'core',
      'toracica_lombar_core',
      'controle_motor',
      'dead',
      'bug',
      'bracos',
      'alternados',
    ],
  },
  {
    nome: 'Prancha frontal com joelhos apoiados',
    slug: 'prancha-frontal-com-joelhos-apoiados',
    area: 'Toracica / lombar / core',
    regiaoCorporal: 'TORACICA_LOMBAR_CORE',
    categoria: 'FORTALECIMENTO',
    nivel: 'INICIANTE',
    tags: [
      'toracica',
      'lombar',
      'core',
      'toracica_lombar_core',
      'fortalecimento',
      'prancha',
      'frontal',
      'com',
      'joelhos',
      'apoiados',
    ],
  },
  {
    nome: 'Prancha frontal inclinada na bancada',
    slug: 'prancha-frontal-inclinada-na-bancada',
    area: 'Toracica / lombar / core',
    regiaoCorporal: 'TORACICA_LOMBAR_CORE',
    categoria: 'FORTALECIMENTO',
    nivel: 'INICIANTE',
    tags: [
      'toracica',
      'lombar',
      'core',
      'toracica_lombar_core',
      'fortalecimento',
      'prancha',
      'frontal',
      'inclinada',
      'bancada',
    ],
  },
  {
    nome: 'Bird dog apenas perna',
    slug: 'bird-dog-apenas-perna',
    area: 'Toracica / lombar / core',
    regiaoCorporal: 'TORACICA_LOMBAR_CORE',
    categoria: 'CONTROLE_MOTOR',
    nivel: 'INICIANTE',
    tags: [
      'toracica',
      'lombar',
      'core',
      'toracica_lombar_core',
      'controle_motor',
      'bird',
      'dog',
      'apenas',
      'perna',
    ],
  },
  {
    nome: 'Bird dog apenas braco',
    slug: 'bird-dog-apenas-braco',
    area: 'Toracica / lombar / core',
    regiaoCorporal: 'TORACICA_LOMBAR_CORE',
    categoria: 'CONTROLE_MOTOR',
    nivel: 'INICIANTE',
    tags: [
      'toracica',
      'lombar',
      'core',
      'toracica_lombar_core',
      'controle_motor',
      'bird',
      'dog',
      'apenas',
      'braco',
    ],
  },
  {
    nome: 'Superman curto em decubito ventral',
    slug: 'superman-curto-em-decubito-ventral',
    area: 'Toracica / lombar / core',
    regiaoCorporal: 'TORACICA_LOMBAR_CORE',
    categoria: 'FORTALECIMENTO',
    nivel: 'INICIANTE',
    tags: [
      'toracica',
      'lombar',
      'core',
      'toracica_lombar_core',
      'fortalecimento',
      'superman',
      'curto',
      'decubito',
      'ventral',
    ],
  },
  {
    nome: 'Extensao lombar prone press up baixa',
    slug: 'extensao-lombar-prone-press-up-baixa',
    area: 'Toracica / lombar / core',
    regiaoCorporal: 'TORACICA_LOMBAR_CORE',
    categoria: 'MOBILIDADE',
    nivel: 'INICIANTE',
    tags: [
      'toracica',
      'lombar',
      'core',
      'toracica_lombar_core',
      'mobilidade',
      'extensao',
      'prone',
      'press',
      'baixa',
    ],
  },
  {
    nome: 'Flexao lombar sentado com apoio',
    slug: 'flexao-lombar-sentado-com-apoio',
    area: 'Toracica / lombar / core',
    regiaoCorporal: 'TORACICA_LOMBAR_CORE',
    categoria: 'MOBILIDADE',
    nivel: 'INICIANTE',
    tags: [
      'toracica',
      'lombar',
      'core',
      'toracica_lombar_core',
      'mobilidade',
      'flexao',
      'sentado',
      'com',
      'apoio',
    ],
  },
  {
    nome: 'Alongamento posicao da crianca lateral',
    slug: 'alongamento-posicao-da-crianca-lateral',
    area: 'Toracica / lombar / core',
    regiaoCorporal: 'TORACICA_LOMBAR_CORE',
    categoria: 'MOBILIDADE',
    nivel: 'INICIANTE',
    tags: [
      'toracica',
      'lombar',
      'core',
      'toracica_lombar_core',
      'mobilidade',
      'alongamento',
      'posicao',
      'crianca',
      'lateral',
    ],
  },
  {
    nome: 'Joelho duplo ao peito',
    slug: 'joelho-duplo-ao-peito',
    area: 'Toracica / lombar / core',
    regiaoCorporal: 'TORACICA_LOMBAR_CORE',
    categoria: 'MOBILIDADE',
    nivel: 'INICIANTE',
    tags: [
      'toracica',
      'lombar',
      'core',
      'toracica_lombar_core',
      'mobilidade',
      'joelho',
      'duplo',
      'peito',
    ],
  },
  {
    nome: 'Deslizamento nervo ciatico sentado',
    slug: 'deslizamento-nervo-ciatico-sentado',
    area: 'Toracica / lombar / core',
    regiaoCorporal: 'TORACICA_LOMBAR_CORE',
    categoria: 'MOBILIDADE_NEURAL',
    nivel: 'INICIANTE',
    tags: [
      'toracica',
      'lombar',
      'core',
      'toracica_lombar_core',
      'mobilidade_neural',
      'deslizamento',
      'nervo',
      'ciatico',
      'sentado',
    ],
  },
  {
    nome: 'Mobilizacao neural ciatica em decubito',
    slug: 'mobilizacao-neural-ciatica-em-decubito',
    area: 'Toracica / lombar / core',
    regiaoCorporal: 'TORACICA_LOMBAR_CORE',
    categoria: 'MOBILIDADE_NEURAL',
    nivel: 'INICIANTE',
    tags: [
      'toracica',
      'lombar',
      'core',
      'toracica_lombar_core',
      'mobilidade_neural',
      'mobilizacao',
      'neural',
      'ciatica',
      'decubito',
    ],
  },
  {
    nome: 'Rotacao lombar com bola entre joelhos',
    slug: 'rotacao-lombar-com-bola-entre-joelhos',
    area: 'Toracica / lombar / core',
    regiaoCorporal: 'TORACICA_LOMBAR_CORE',
    categoria: 'MOBILIDADE',
    nivel: 'INICIANTE',
    tags: [
      'toracica',
      'lombar',
      'core',
      'toracica_lombar_core',
      'mobilidade',
      'rotacao',
      'com',
      'bola',
      'entre',
      'joelhos',
    ],
  },
  {
    nome: 'Anti rotacao pallof press leve',
    slug: 'anti-rotacao-pallof-press-leve',
    area: 'Toracica / lombar / core',
    regiaoCorporal: 'TORACICA_LOMBAR_CORE',
    categoria: 'CONTROLE_MOTOR',
    nivel: 'INICIANTE',
    tags: [
      'toracica',
      'lombar',
      'core',
      'toracica_lombar_core',
      'controle_motor',
      'anti',
      'rotacao',
      'pallof',
      'press',
      'leve',
    ],
  },
  {
    nome: 'Caminhada do fazendeiro leve',
    slug: 'caminhada-do-fazendeiro-leve',
    area: 'Toracica / lombar / core',
    regiaoCorporal: 'TORACICA_LOMBAR_CORE',
    categoria: 'FUNCIONAL',
    nivel: 'INICIANTE',
    tags: [
      'toracica',
      'lombar',
      'core',
      'toracica_lombar_core',
      'funcional',
      'caminhada',
      'fazendeiro',
      'leve',
    ],
  },
  {
    nome: 'Marcha em ponte curta',
    slug: 'marcha-em-ponte-curta',
    area: 'Toracica / lombar / core',
    regiaoCorporal: 'TORACICA_LOMBAR_CORE',
    categoria: 'FORTALECIMENTO',
    nivel: 'INICIANTE',
    tags: [
      'toracica',
      'lombar',
      'core',
      'toracica_lombar_core',
      'fortalecimento',
      'marcha',
      'ponte',
      'curta',
    ],
  },
  {
    nome: 'Controle abdominal em sedestacao',
    slug: 'controle-abdominal-em-sedestacao',
    area: 'Toracica / lombar / core',
    regiaoCorporal: 'TORACICA_LOMBAR_CORE',
    categoria: 'CONTROLE_MOTOR',
    nivel: 'INICIANTE',
    tags: [
      'toracica',
      'lombar',
      'core',
      'toracica_lombar_core',
      'controle_motor',
      'controle',
      'abdominal',
      'sedestacao',
    ],
  },
  {
    nome: 'Estabilidade lombar com bola na parede',
    slug: 'estabilidade-lombar-com-bola-na-parede',
    area: 'Toracica / lombar / core',
    regiaoCorporal: 'TORACICA_LOMBAR_CORE',
    categoria: 'CONTROLE_MOTOR',
    nivel: 'INICIANTE',
    tags: [
      'toracica',
      'lombar',
      'core',
      'toracica_lombar_core',
      'controle_motor',
      'estabilidade',
      'com',
      'bola',
      'parede',
    ],
  },
  {
    nome: 'Mobilidade pendular circular de ombro',
    slug: 'mobilidade-pendular-circular-de-ombro',
    area: 'Ombro / escapula',
    regiaoCorporal: 'OMBRO_ESCAPULA',
    categoria: 'MOBILIDADE',
    nivel: 'INICIANTE',
    tags: [
      'ombro',
      'escapula',
      'ombro_escapula',
      'mobilidade',
      'pendular',
      'circular',
    ],
  },
  {
    nome: 'Pendular ombro lateral',
    slug: 'pendular-ombro-lateral',
    area: 'Ombro / escapula',
    regiaoCorporal: 'OMBRO_ESCAPULA',
    categoria: 'MOBILIDADE',
    nivel: 'INICIANTE',
    tags: [
      'ombro',
      'escapula',
      'ombro_escapula',
      'mobilidade',
      'pendular',
      'lateral',
    ],
  },
  {
    nome: 'Flexao de ombro com polia',
    slug: 'flexao-de-ombro-com-polia',
    area: 'Ombro / escapula',
    regiaoCorporal: 'OMBRO_ESCAPULA',
    categoria: 'MOBILIDADE',
    nivel: 'INICIANTE',
    tags: [
      'ombro',
      'escapula',
      'ombro_escapula',
      'mobilidade',
      'flexao',
      'com',
      'polia',
    ],
  },
  {
    nome: 'Abducao de ombro com polia',
    slug: 'abducao-de-ombro-com-polia',
    area: 'Ombro / escapula',
    regiaoCorporal: 'OMBRO_ESCAPULA',
    categoria: 'MOBILIDADE',
    nivel: 'INICIANTE',
    tags: [
      'ombro',
      'escapula',
      'ombro_escapula',
      'mobilidade',
      'abducao',
      'com',
      'polia',
    ],
  },
  {
    nome: 'Rotacao externa de ombro com bastao',
    slug: 'rotacao-externa-de-ombro-com-bastao',
    area: 'Ombro / escapula',
    regiaoCorporal: 'OMBRO_ESCAPULA',
    categoria: 'MOBILIDADE',
    nivel: 'INICIANTE',
    tags: [
      'ombro',
      'escapula',
      'ombro_escapula',
      'mobilidade',
      'rotacao',
      'externa',
      'com',
      'bastao',
    ],
  },
  {
    nome: 'Rotacao interna de ombro com bastao',
    slug: 'rotacao-interna-de-ombro-com-bastao',
    area: 'Ombro / escapula',
    regiaoCorporal: 'OMBRO_ESCAPULA',
    categoria: 'MOBILIDADE',
    nivel: 'INICIANTE',
    tags: [
      'ombro',
      'escapula',
      'ombro_escapula',
      'mobilidade',
      'rotacao',
      'interna',
      'com',
      'bastao',
    ],
  },
  {
    nome: 'Alongamento capsula posterior do ombro',
    slug: 'alongamento-capsula-posterior-do-ombro',
    area: 'Ombro / escapula',
    regiaoCorporal: 'OMBRO_ESCAPULA',
    categoria: 'MOBILIDADE',
    nivel: 'INICIANTE',
    tags: [
      'ombro',
      'escapula',
      'ombro_escapula',
      'mobilidade',
      'alongamento',
      'capsula',
      'posterior',
    ],
  },
  {
    nome: 'Alongamento cruzado posterior de ombro',
    slug: 'alongamento-cruzado-posterior-de-ombro',
    area: 'Ombro / escapula',
    regiaoCorporal: 'OMBRO_ESCAPULA',
    categoria: 'MOBILIDADE',
    nivel: 'INICIANTE',
    tags: [
      'ombro',
      'escapula',
      'ombro_escapula',
      'mobilidade',
      'alongamento',
      'cruzado',
      'posterior',
    ],
  },
  {
    nome: 'Alongamento peitoral menor no canto',
    slug: 'alongamento-peitoral-menor-no-canto',
    area: 'Ombro / escapula',
    regiaoCorporal: 'OMBRO_ESCAPULA',
    categoria: 'MOBILIDADE',
    nivel: 'INICIANTE',
    tags: [
      'ombro',
      'escapula',
      'ombro_escapula',
      'mobilidade',
      'alongamento',
      'peitoral',
      'menor',
      'canto',
    ],
  },
  {
    nome: 'Retracao escapular com faixa em pe',
    slug: 'retracao-escapular-com-faixa-em-pe',
    area: 'Ombro / escapula',
    regiaoCorporal: 'OMBRO_ESCAPULA',
    categoria: 'CONTROLE_MOTOR',
    nivel: 'INICIANTE',
    tags: [
      'ombro',
      'escapula',
      'ombro_escapula',
      'controle_motor',
      'retracao',
      'escapular',
      'com',
      'faixa',
    ],
  },
  {
    nome: 'Depressao escapular sentada',
    slug: 'depressao-escapular-sentada',
    area: 'Ombro / escapula',
    regiaoCorporal: 'OMBRO_ESCAPULA',
    categoria: 'CONTROLE_MOTOR',
    nivel: 'INICIANTE',
    tags: [
      'ombro',
      'escapula',
      'ombro_escapula',
      'controle_motor',
      'depressao',
      'escapular',
      'sentada',
    ],
  },
  {
    nome: 'Elevacao escapular controlada',
    slug: 'elevacao-escapular-controlada',
    area: 'Ombro / escapula',
    regiaoCorporal: 'OMBRO_ESCAPULA',
    categoria: 'CONTROLE_MOTOR',
    nivel: 'INICIANTE',
    tags: [
      'ombro',
      'escapula',
      'ombro_escapula',
      'controle_motor',
      'elevacao',
      'escapular',
      'controlada',
    ],
  },
  {
    nome: 'Protracao escapular na parede',
    slug: 'protracao-escapular-na-parede',
    area: 'Ombro / escapula',
    regiaoCorporal: 'OMBRO_ESCAPULA',
    categoria: 'CONTROLE_MOTOR',
    nivel: 'INICIANTE',
    tags: [
      'ombro',
      'escapula',
      'ombro_escapula',
      'controle_motor',
      'protracao',
      'escapular',
      'parede',
    ],
  },
  {
    nome: 'Push plus na parede',
    slug: 'push-plus-na-parede',
    area: 'Ombro / escapula',
    regiaoCorporal: 'OMBRO_ESCAPULA',
    categoria: 'CONTROLE_MOTOR',
    nivel: 'INICIANTE',
    tags: [
      'ombro',
      'escapula',
      'ombro_escapula',
      'controle_motor',
      'push',
      'plus',
      'parede',
    ],
  },
  {
    nome: 'Serratil slide com rolo',
    slug: 'serratil-slide-com-rolo',
    area: 'Ombro / escapula',
    regiaoCorporal: 'OMBRO_ESCAPULA',
    categoria: 'CONTROLE_MOTOR',
    nivel: 'INICIANTE',
    tags: [
      'ombro',
      'escapula',
      'ombro_escapula',
      'controle_motor',
      'serratil',
      'slide',
      'com',
      'rolo',
    ],
  },
  {
    nome: 'Y na parede baixo',
    slug: 'y-na-parede-baixo',
    area: 'Ombro / escapula',
    regiaoCorporal: 'OMBRO_ESCAPULA',
    categoria: 'CONTROLE_MOTOR',
    nivel: 'INICIANTE',
    tags: [
      'ombro',
      'escapula',
      'ombro_escapula',
      'controle_motor',
      'parede',
      'baixo',
    ],
  },
  {
    nome: 'T inclinado sem carga',
    slug: 't-inclinado-sem-carga',
    area: 'Ombro / escapula',
    regiaoCorporal: 'OMBRO_ESCAPULA',
    categoria: 'FORTALECIMENTO',
    nivel: 'INICIANTE',
    tags: [
      'ombro',
      'escapula',
      'ombro_escapula',
      'fortalecimento',
      'inclinado',
      'sem',
      'carga',
    ],
  },
  {
    nome: 'W escapular em pe',
    slug: 'w-escapular-em-pe',
    area: 'Ombro / escapula',
    regiaoCorporal: 'OMBRO_ESCAPULA',
    categoria: 'CONTROLE_MOTOR',
    nivel: 'INICIANTE',
    tags: [
      'ombro',
      'escapula',
      'ombro_escapula',
      'controle_motor',
      'escapular',
    ],
  },
  {
    nome: 'Remada baixa com faixa',
    slug: 'remada-baixa-com-faixa',
    area: 'Ombro / escapula',
    regiaoCorporal: 'OMBRO_ESCAPULA',
    categoria: 'FORTALECIMENTO',
    nivel: 'INICIANTE',
    tags: [
      'ombro',
      'escapula',
      'ombro_escapula',
      'fortalecimento',
      'remada',
      'baixa',
      'com',
      'faixa',
    ],
  },
  {
    nome: 'Remada alta com faixa leve',
    slug: 'remada-alta-com-faixa-leve',
    area: 'Ombro / escapula',
    regiaoCorporal: 'OMBRO_ESCAPULA',
    categoria: 'FORTALECIMENTO',
    nivel: 'INICIANTE',
    tags: [
      'ombro',
      'escapula',
      'ombro_escapula',
      'fortalecimento',
      'remada',
      'alta',
      'com',
      'faixa',
      'leve',
    ],
  },
  {
    nome: 'Extensao de ombro em decubito ventral',
    slug: 'extensao-de-ombro-em-decubito-ventral',
    area: 'Ombro / escapula',
    regiaoCorporal: 'OMBRO_ESCAPULA',
    categoria: 'FORTALECIMENTO',
    nivel: 'INICIANTE',
    tags: [
      'ombro',
      'escapula',
      'ombro_escapula',
      'fortalecimento',
      'extensao',
      'decubito',
      'ventral',
    ],
  },
  {
    nome: 'Rotacao externa ombro decubito lateral',
    slug: 'rotacao-externa-ombro-decubito-lateral',
    area: 'Ombro / escapula',
    regiaoCorporal: 'OMBRO_ESCAPULA',
    categoria: 'FORTALECIMENTO',
    nivel: 'INICIANTE',
    tags: [
      'ombro',
      'escapula',
      'ombro_escapula',
      'fortalecimento',
      'rotacao',
      'externa',
      'decubito',
      'lateral',
    ],
  },
  {
    nome: 'Rotacao interna ombro deitado',
    slug: 'rotacao-interna-ombro-deitado',
    area: 'Ombro / escapula',
    regiaoCorporal: 'OMBRO_ESCAPULA',
    categoria: 'FORTALECIMENTO',
    nivel: 'INICIANTE',
    tags: [
      'ombro',
      'escapula',
      'ombro_escapula',
      'fortalecimento',
      'rotacao',
      'interna',
      'deitado',
    ],
  },
  {
    nome: 'Abducao de ombro decubito lateral',
    slug: 'abducao-de-ombro-decubito-lateral',
    area: 'Ombro / escapula',
    regiaoCorporal: 'OMBRO_ESCAPULA',
    categoria: 'FORTALECIMENTO',
    nivel: 'INICIANTE',
    tags: [
      'ombro',
      'escapula',
      'ombro_escapula',
      'fortalecimento',
      'abducao',
      'decubito',
      'lateral',
    ],
  },
  {
    nome: 'Flexao de ombro deitado com halter leve',
    slug: 'flexao-de-ombro-deitado-com-halter-leve',
    area: 'Ombro / escapula',
    regiaoCorporal: 'OMBRO_ESCAPULA',
    categoria: 'FORTALECIMENTO',
    nivel: 'INICIANTE',
    tags: [
      'ombro',
      'escapula',
      'ombro_escapula',
      'fortalecimento',
      'flexao',
      'deitado',
      'com',
      'halter',
      'leve',
    ],
  },
  {
    nome: 'Escapular setting em decubito ventral',
    slug: 'escapular-setting-em-decubito-ventral',
    area: 'Ombro / escapula',
    regiaoCorporal: 'OMBRO_ESCAPULA',
    categoria: 'CONTROLE_MOTOR',
    nivel: 'INICIANTE',
    tags: [
      'ombro',
      'escapula',
      'ombro_escapula',
      'controle_motor',
      'escapular',
      'setting',
      'decubito',
      'ventral',
    ],
  },
  {
    nome: 'Elevacao frontal com faixa',
    slug: 'elevacao-frontal-com-faixa',
    area: 'Ombro / escapula',
    regiaoCorporal: 'OMBRO_ESCAPULA',
    categoria: 'FORTALECIMENTO',
    nivel: 'INICIANTE',
    tags: [
      'ombro',
      'escapula',
      'ombro_escapula',
      'fortalecimento',
      'elevacao',
      'frontal',
      'com',
      'faixa',
    ],
  },
  {
    nome: 'Elevacao lateral com faixa',
    slug: 'elevacao-lateral-com-faixa',
    area: 'Ombro / escapula',
    regiaoCorporal: 'OMBRO_ESCAPULA',
    categoria: 'FORTALECIMENTO',
    nivel: 'INICIANTE',
    tags: [
      'ombro',
      'escapula',
      'ombro_escapula',
      'fortalecimento',
      'elevacao',
      'lateral',
      'com',
      'faixa',
    ],
  },
  {
    nome: 'Face pull com faixa leve',
    slug: 'face-pull-com-faixa-leve',
    area: 'Ombro / escapula',
    regiaoCorporal: 'OMBRO_ESCAPULA',
    categoria: 'FORTALECIMENTO',
    nivel: 'INICIANTE',
    tags: [
      'ombro',
      'escapula',
      'ombro_escapula',
      'fortalecimento',
      'face',
      'pull',
      'com',
      'faixa',
      'leve',
    ],
  },
  {
    nome: 'Estabilizacao ombro bola na parede',
    slug: 'estabilizacao-ombro-bola-na-parede',
    area: 'Ombro / escapula',
    regiaoCorporal: 'OMBRO_ESCAPULA',
    categoria: 'CONTROLE_MOTOR',
    nivel: 'INICIANTE',
    tags: [
      'ombro',
      'escapula',
      'ombro_escapula',
      'controle_motor',
      'estabilizacao',
      'bola',
      'parede',
    ],
  },
  {
    nome: 'Isometria flexao de cotovelo',
    slug: 'isometria-flexao-de-cotovelo',
    area: 'Cotovelo / punho / mao',
    regiaoCorporal: 'COTOVELO_PUNHO_MAO',
    categoria: 'FORTALECIMENTO',
    nivel: 'INICIANTE',
    tags: [
      'cotovelo',
      'punho',
      'mao',
      'cotovelo_punho_mao',
      'fortalecimento',
      'isometria',
      'flexao',
    ],
  },
  {
    nome: 'Isometria extensao de cotovelo',
    slug: 'isometria-extensao-de-cotovelo',
    area: 'Cotovelo / punho / mao',
    regiaoCorporal: 'COTOVELO_PUNHO_MAO',
    categoria: 'FORTALECIMENTO',
    nivel: 'INICIANTE',
    tags: [
      'cotovelo',
      'punho',
      'mao',
      'cotovelo_punho_mao',
      'fortalecimento',
      'isometria',
      'extensao',
    ],
  },
  {
    nome: 'Alongamento flexores do punho cotovelo estendido',
    slug: 'alongamento-flexores-do-punho-cotovelo-estendido',
    area: 'Cotovelo / punho / mao',
    regiaoCorporal: 'COTOVELO_PUNHO_MAO',
    categoria: 'MOBILIDADE',
    nivel: 'INICIANTE',
    tags: [
      'cotovelo',
      'punho',
      'mao',
      'cotovelo_punho_mao',
      'mobilidade',
      'alongamento',
      'flexores',
      'estendido',
    ],
  },
  {
    nome: 'Alongamento extensores do punho cotovelo estendido',
    slug: 'alongamento-extensores-do-punho-cotovelo-estendido',
    area: 'Cotovelo / punho / mao',
    regiaoCorporal: 'COTOVELO_PUNHO_MAO',
    categoria: 'MOBILIDADE',
    nivel: 'INICIANTE',
    tags: [
      'cotovelo',
      'punho',
      'mao',
      'cotovelo_punho_mao',
      'mobilidade',
      'alongamento',
      'extensores',
      'estendido',
    ],
  },
  {
    nome: 'Flexao de punho com halter',
    slug: 'flexao-de-punho-com-halter',
    area: 'Cotovelo / punho / mao',
    regiaoCorporal: 'COTOVELO_PUNHO_MAO',
    categoria: 'FORTALECIMENTO',
    nivel: 'INICIANTE',
    tags: [
      'cotovelo',
      'punho',
      'mao',
      'cotovelo_punho_mao',
      'fortalecimento',
      'flexao',
      'com',
      'halter',
    ],
  },
  {
    nome: 'Extensao de punho com halter',
    slug: 'extensao-de-punho-com-halter',
    area: 'Cotovelo / punho / mao',
    regiaoCorporal: 'COTOVELO_PUNHO_MAO',
    categoria: 'FORTALECIMENTO',
    nivel: 'INICIANTE',
    tags: [
      'cotovelo',
      'punho',
      'mao',
      'cotovelo_punho_mao',
      'fortalecimento',
      'extensao',
      'com',
      'halter',
    ],
  },
  {
    nome: 'Desvio radial com halter',
    slug: 'desvio-radial-com-halter',
    area: 'Cotovelo / punho / mao',
    regiaoCorporal: 'COTOVELO_PUNHO_MAO',
    categoria: 'FORTALECIMENTO',
    nivel: 'INICIANTE',
    tags: [
      'cotovelo',
      'punho',
      'mao',
      'cotovelo_punho_mao',
      'fortalecimento',
      'desvio',
      'radial',
      'com',
      'halter',
    ],
  },
  {
    nome: 'Desvio ulnar com halter',
    slug: 'desvio-ulnar-com-halter',
    area: 'Cotovelo / punho / mao',
    regiaoCorporal: 'COTOVELO_PUNHO_MAO',
    categoria: 'FORTALECIMENTO',
    nivel: 'INICIANTE',
    tags: [
      'cotovelo',
      'punho',
      'mao',
      'cotovelo_punho_mao',
      'fortalecimento',
      'desvio',
      'ulnar',
      'com',
      'halter',
    ],
  },
  {
    nome: 'Pronacao com martelo',
    slug: 'pronacao-com-martelo',
    area: 'Cotovelo / punho / mao',
    regiaoCorporal: 'COTOVELO_PUNHO_MAO',
    categoria: 'FORTALECIMENTO',
    nivel: 'INICIANTE',
    tags: [
      'cotovelo',
      'punho',
      'mao',
      'cotovelo_punho_mao',
      'fortalecimento',
      'pronacao',
      'com',
      'martelo',
    ],
  },
  {
    nome: 'Supinacao com martelo',
    slug: 'supinacao-com-martelo',
    area: 'Cotovelo / punho / mao',
    regiaoCorporal: 'COTOVELO_PUNHO_MAO',
    categoria: 'FORTALECIMENTO',
    nivel: 'INICIANTE',
    tags: [
      'cotovelo',
      'punho',
      'mao',
      'cotovelo_punho_mao',
      'fortalecimento',
      'supinacao',
      'com',
      'martelo',
    ],
  },
  {
    nome: 'Aperto de toalha enrolada',
    slug: 'aperto-de-toalha-enrolada',
    area: 'Cotovelo / punho / mao',
    regiaoCorporal: 'COTOVELO_PUNHO_MAO',
    categoria: 'FORTALECIMENTO',
    nivel: 'INICIANTE',
    tags: [
      'cotovelo',
      'punho',
      'mao',
      'cotovelo_punho_mao',
      'fortalecimento',
      'aperto',
      'toalha',
      'enrolada',
    ],
  },
  {
    nome: 'Pinca polegar indicador',
    slug: 'pinca-polegar-indicador',
    area: 'Cotovelo / punho / mao',
    regiaoCorporal: 'COTOVELO_PUNHO_MAO',
    categoria: 'CONTROLE_MOTOR',
    nivel: 'INICIANTE',
    tags: [
      'cotovelo',
      'punho',
      'mao',
      'cotovelo_punho_mao',
      'controle_motor',
      'pinca',
      'polegar',
      'indicador',
    ],
  },
  {
    nome: 'Pinca chave com massa',
    slug: 'pinca-chave-com-massa',
    area: 'Cotovelo / punho / mao',
    regiaoCorporal: 'COTOVELO_PUNHO_MAO',
    categoria: 'FORTALECIMENTO',
    nivel: 'INICIANTE',
    tags: [
      'cotovelo',
      'punho',
      'mao',
      'cotovelo_punho_mao',
      'fortalecimento',
      'pinca',
      'chave',
      'com',
      'massa',
    ],
  },
  {
    nome: 'Extensao polegar com elastico',
    slug: 'extensao-polegar-com-elastico',
    area: 'Cotovelo / punho / mao',
    regiaoCorporal: 'COTOVELO_PUNHO_MAO',
    categoria: 'FORTALECIMENTO',
    nivel: 'INICIANTE',
    tags: [
      'cotovelo',
      'punho',
      'mao',
      'cotovelo_punho_mao',
      'fortalecimento',
      'extensao',
      'polegar',
      'com',
      'elastico',
    ],
  },
  {
    nome: 'Abducao polegar com elastico',
    slug: 'abducao-polegar-com-elastico',
    area: 'Cotovelo / punho / mao',
    regiaoCorporal: 'COTOVELO_PUNHO_MAO',
    categoria: 'FORTALECIMENTO',
    nivel: 'INICIANTE',
    tags: [
      'cotovelo',
      'punho',
      'mao',
      'cotovelo_punho_mao',
      'fortalecimento',
      'abducao',
      'polegar',
      'com',
      'elastico',
    ],
  },
  {
    nome: 'Deslizamento tendinoso punho mao',
    slug: 'deslizamento-tendinoso-punho-mao',
    area: 'Cotovelo / punho / mao',
    regiaoCorporal: 'COTOVELO_PUNHO_MAO',
    categoria: 'MOBILIDADE',
    nivel: 'INICIANTE',
    tags: [
      'cotovelo',
      'punho',
      'mao',
      'cotovelo_punho_mao',
      'mobilidade',
      'deslizamento',
      'tendinoso',
    ],
  },
  {
    nome: 'Gancho de dedos ativo',
    slug: 'gancho-de-dedos-ativo',
    area: 'Cotovelo / punho / mao',
    regiaoCorporal: 'COTOVELO_PUNHO_MAO',
    categoria: 'MOBILIDADE',
    nivel: 'INICIANTE',
    tags: [
      'cotovelo',
      'punho',
      'mao',
      'cotovelo_punho_mao',
      'mobilidade',
      'gancho',
      'dedos',
      'ativo',
    ],
  },
  {
    nome: 'Punho cerrado e aberto ativo',
    slug: 'punho-cerrado-e-aberto-ativo',
    area: 'Cotovelo / punho / mao',
    regiaoCorporal: 'COTOVELO_PUNHO_MAO',
    categoria: 'MOBILIDADE',
    nivel: 'INICIANTE',
    tags: [
      'cotovelo',
      'punho',
      'mao',
      'cotovelo_punho_mao',
      'mobilidade',
      'cerrado',
      'aberto',
      'ativo',
    ],
  },
  {
    nome: 'Oposicao polegar sequencial',
    slug: 'oposicao-polegar-sequencial',
    area: 'Cotovelo / punho / mao',
    regiaoCorporal: 'COTOVELO_PUNHO_MAO',
    categoria: 'CONTROLE_MOTOR',
    nivel: 'INICIANTE',
    tags: [
      'cotovelo',
      'punho',
      'mao',
      'cotovelo_punho_mao',
      'controle_motor',
      'oposicao',
      'polegar',
      'sequencial',
    ],
  },
  {
    nome: 'Mobilidade cotovelo flexao extensao ativa',
    slug: 'mobilidade-cotovelo-flexao-extensao-ativa',
    area: 'Cotovelo / punho / mao',
    regiaoCorporal: 'COTOVELO_PUNHO_MAO',
    categoria: 'MOBILIDADE',
    nivel: 'INICIANTE',
    tags: [
      'cotovelo',
      'punho',
      'mao',
      'cotovelo_punho_mao',
      'mobilidade',
      'flexao',
      'extensao',
      'ativa',
    ],
  },
  {
    nome: 'Alongamento pronadores do antebraco',
    slug: 'alongamento-pronadores-do-antebraco',
    area: 'Cotovelo / punho / mao',
    regiaoCorporal: 'COTOVELO_PUNHO_MAO',
    categoria: 'MOBILIDADE',
    nivel: 'INICIANTE',
    tags: [
      'cotovelo',
      'punho',
      'mao',
      'cotovelo_punho_mao',
      'mobilidade',
      'alongamento',
      'pronadores',
      'antebraco',
    ],
  },
  {
    nome: 'Alongamento supinadores do antebraco',
    slug: 'alongamento-supinadores-do-antebraco',
    area: 'Cotovelo / punho / mao',
    regiaoCorporal: 'COTOVELO_PUNHO_MAO',
    categoria: 'MOBILIDADE',
    nivel: 'INICIANTE',
    tags: [
      'cotovelo',
      'punho',
      'mao',
      'cotovelo_punho_mao',
      'mobilidade',
      'alongamento',
      'supinadores',
      'antebraco',
    ],
  },
  {
    nome: 'Rotacao externa de quadril sentada',
    slug: 'rotacao-externa-de-quadril-sentada',
    area: 'Quadril / pelve',
    regiaoCorporal: 'QUADRIL_PELVE',
    categoria: 'MOBILIDADE',
    nivel: 'INICIANTE',
    tags: [
      'quadril',
      'pelve',
      'quadril_pelve',
      'mobilidade',
      'rotacao',
      'externa',
      'sentada',
    ],
  },
  {
    nome: 'Rotacao interna de quadril sentada',
    slug: 'rotacao-interna-de-quadril-sentada',
    area: 'Quadril / pelve',
    regiaoCorporal: 'QUADRIL_PELVE',
    categoria: 'MOBILIDADE',
    nivel: 'INICIANTE',
    tags: [
      'quadril',
      'pelve',
      'quadril_pelve',
      'mobilidade',
      'rotacao',
      'interna',
      'sentada',
    ],
  },
  {
    nome: 'Rotacao quadril noventa noventa sentado',
    slug: 'rotacao-quadril-noventa-noventa-sentado',
    area: 'Quadril / pelve',
    regiaoCorporal: 'QUADRIL_PELVE',
    categoria: 'MOBILIDADE',
    nivel: 'INICIANTE',
    tags: [
      'quadril',
      'pelve',
      'quadril_pelve',
      'mobilidade',
      'rotacao',
      'noventa',
      'sentado',
    ],
  },
  {
    nome: 'Mobilidade quadril quatro apoios rock back',
    slug: 'mobilidade-quadril-quatro-apoios-rock-back',
    area: 'Quadril / pelve',
    regiaoCorporal: 'QUADRIL_PELVE',
    categoria: 'MOBILIDADE',
    nivel: 'INICIANTE',
    tags: [
      'quadril',
      'pelve',
      'quadril_pelve',
      'mobilidade',
      'quatro',
      'apoios',
      'rock',
      'back',
    ],
  },
  {
    nome: 'Alongamento adutores borboleta',
    slug: 'alongamento-adutores-borboleta',
    area: 'Quadril / pelve',
    regiaoCorporal: 'QUADRIL_PELVE',
    categoria: 'MOBILIDADE',
    nivel: 'INICIANTE',
    tags: [
      'quadril',
      'pelve',
      'quadril_pelve',
      'mobilidade',
      'alongamento',
      'adutores',
      'borboleta',
    ],
  },
  {
    nome: 'Alongamento adutores lateral',
    slug: 'alongamento-adutores-lateral',
    area: 'Quadril / pelve',
    regiaoCorporal: 'QUADRIL_PELVE',
    categoria: 'MOBILIDADE',
    nivel: 'INICIANTE',
    tags: [
      'quadril',
      'pelve',
      'quadril_pelve',
      'mobilidade',
      'alongamento',
      'adutores',
      'lateral',
    ],
  },
  {
    nome: 'Alongamento gluteo sentado',
    slug: 'alongamento-gluteo-sentado',
    area: 'Quadril / pelve',
    regiaoCorporal: 'QUADRIL_PELVE',
    categoria: 'MOBILIDADE',
    nivel: 'INICIANTE',
    tags: [
      'quadril',
      'pelve',
      'quadril_pelve',
      'mobilidade',
      'alongamento',
      'gluteo',
      'sentado',
    ],
  },
  {
    nome: 'Alongamento flexor quadril em pe',
    slug: 'alongamento-flexor-quadril-em-pe',
    area: 'Quadril / pelve',
    regiaoCorporal: 'QUADRIL_PELVE',
    categoria: 'MOBILIDADE',
    nivel: 'INICIANTE',
    tags: [
      'quadril',
      'pelve',
      'quadril_pelve',
      'mobilidade',
      'alongamento',
      'flexor',
    ],
  },
  {
    nome: 'Isometria gluteo em decubito',
    slug: 'isometria-gluteo-em-decubito',
    area: 'Quadril / pelve',
    regiaoCorporal: 'QUADRIL_PELVE',
    categoria: 'FORTALECIMENTO',
    nivel: 'INICIANTE',
    tags: [
      'quadril',
      'pelve',
      'quadril_pelve',
      'fortalecimento',
      'isometria',
      'gluteo',
      'decubito',
    ],
  },
  {
    nome: 'Isometria abdutores contra parede',
    slug: 'isometria-abdutores-contra-parede',
    area: 'Quadril / pelve',
    regiaoCorporal: 'QUADRIL_PELVE',
    categoria: 'FORTALECIMENTO',
    nivel: 'INICIANTE',
    tags: [
      'quadril',
      'pelve',
      'quadril_pelve',
      'fortalecimento',
      'isometria',
      'abdutores',
      'contra',
      'parede',
    ],
  },
  {
    nome: 'Abducao quadril em pe sem faixa',
    slug: 'abducao-quadril-em-pe-sem-faixa',
    area: 'Quadril / pelve',
    regiaoCorporal: 'QUADRIL_PELVE',
    categoria: 'FORTALECIMENTO',
    nivel: 'INICIANTE',
    tags: [
      'quadril',
      'pelve',
      'quadril_pelve',
      'fortalecimento',
      'abducao',
      'sem',
      'faixa',
    ],
  },
  {
    nome: 'Aducao quadril decubito lateral',
    slug: 'aducao-quadril-decubito-lateral',
    area: 'Quadril / pelve',
    regiaoCorporal: 'QUADRIL_PELVE',
    categoria: 'FORTALECIMENTO',
    nivel: 'INICIANTE',
    tags: [
      'quadril',
      'pelve',
      'quadril_pelve',
      'fortalecimento',
      'aducao',
      'decubito',
      'lateral',
    ],
  },
  {
    nome: 'Extensao quadril em pe com apoio',
    slug: 'extensao-quadril-em-pe-com-apoio',
    area: 'Quadril / pelve',
    regiaoCorporal: 'QUADRIL_PELVE',
    categoria: 'FORTALECIMENTO',
    nivel: 'INICIANTE',
    tags: [
      'quadril',
      'pelve',
      'quadril_pelve',
      'fortalecimento',
      'extensao',
      'com',
      'apoio',
    ],
  },
  {
    nome: 'Flexao quadril em pe com apoio',
    slug: 'flexao-quadril-em-pe-com-apoio',
    area: 'Quadril / pelve',
    regiaoCorporal: 'QUADRIL_PELVE',
    categoria: 'FORTALECIMENTO',
    nivel: 'INICIANTE',
    tags: [
      'quadril',
      'pelve',
      'quadril_pelve',
      'fortalecimento',
      'flexao',
      'com',
      'apoio',
    ],
  },
  {
    nome: 'Marcha com mini band',
    slug: 'marcha-com-mini-band',
    area: 'Quadril / pelve',
    regiaoCorporal: 'QUADRIL_PELVE',
    categoria: 'FORTALECIMENTO',
    nivel: 'INICIANTE',
    tags: [
      'quadril',
      'pelve',
      'quadril_pelve',
      'fortalecimento',
      'marcha',
      'com',
      'mini',
      'band',
    ],
  },
  {
    nome: 'Monster walk com faixa',
    slug: 'monster-walk-com-faixa',
    area: 'Quadril / pelve',
    regiaoCorporal: 'QUADRIL_PELVE',
    categoria: 'FORTALECIMENTO',
    nivel: 'INICIANTE',
    tags: [
      'quadril',
      'pelve',
      'quadril_pelve',
      'fortalecimento',
      'monster',
      'walk',
      'com',
      'faixa',
    ],
  },
  {
    nome: 'Ponte unilateral curta',
    slug: 'ponte-unilateral-curta',
    area: 'Quadril / pelve',
    regiaoCorporal: 'QUADRIL_PELVE',
    categoria: 'FORTALECIMENTO',
    nivel: 'INICIANTE',
    tags: [
      'quadril',
      'pelve',
      'quadril_pelve',
      'fortalecimento',
      'ponte',
      'unilateral',
      'curta',
    ],
  },
  {
    nome: 'Ponte com bola suica',
    slug: 'ponte-com-bola-suica',
    area: 'Quadril / pelve',
    regiaoCorporal: 'QUADRIL_PELVE',
    categoria: 'FORTALECIMENTO',
    nivel: 'INICIANTE',
    tags: [
      'quadril',
      'pelve',
      'quadril_pelve',
      'fortalecimento',
      'ponte',
      'com',
      'bola',
      'suica',
    ],
  },
  {
    nome: 'Hip thrust em banco baixo',
    slug: 'hip-thrust-em-banco-baixo',
    area: 'Quadril / pelve',
    regiaoCorporal: 'QUADRIL_PELVE',
    categoria: 'FORTALECIMENTO',
    nivel: 'INICIANTE',
    tags: [
      'quadril',
      'pelve',
      'quadril_pelve',
      'fortalecimento',
      'hip',
      'thrust',
      'banco',
      'baixo',
    ],
  },
  {
    nome: 'Elevacao lateral quadril prancha joelhos',
    slug: 'elevacao-lateral-quadril-prancha-joelhos',
    area: 'Quadril / pelve',
    regiaoCorporal: 'QUADRIL_PELVE',
    categoria: 'FORTALECIMENTO',
    nivel: 'INICIANTE',
    tags: [
      'quadril',
      'pelve',
      'quadril_pelve',
      'fortalecimento',
      'elevacao',
      'lateral',
      'prancha',
      'joelhos',
    ],
  },
  {
    nome: 'Good morning com bastao',
    slug: 'good-morning-com-bastao',
    area: 'Quadril / pelve',
    regiaoCorporal: 'QUADRIL_PELVE',
    categoria: 'CONTROLE_MOTOR',
    nivel: 'INICIANTE',
    tags: [
      'quadril',
      'pelve',
      'quadril_pelve',
      'controle_motor',
      'good',
      'morning',
      'com',
      'bastao',
    ],
  },
  {
    nome: 'Agachamento sumo assistido',
    slug: 'agachamento-sumo-assistido',
    area: 'Quadril / pelve',
    regiaoCorporal: 'QUADRIL_PELVE',
    categoria: 'FUNCIONAL',
    nivel: 'INICIANTE',
    tags: [
      'quadril',
      'pelve',
      'quadril_pelve',
      'funcional',
      'agachamento',
      'sumo',
      'assistido',
    ],
  },
  {
    nome: 'Transferencia de peso lateral quadril',
    slug: 'transferencia-de-peso-lateral-quadril',
    area: 'Quadril / pelve',
    regiaoCorporal: 'QUADRIL_PELVE',
    categoria: 'CONTROLE_MOTOR',
    nivel: 'INICIANTE',
    tags: [
      'quadril',
      'pelve',
      'quadril_pelve',
      'controle_motor',
      'transferencia',
      'peso',
      'lateral',
    ],
  },
  {
    nome: 'Step lateral baixo',
    slug: 'step-lateral-baixo',
    area: 'Quadril / pelve',
    regiaoCorporal: 'QUADRIL_PELVE',
    categoria: 'FUNCIONAL',
    nivel: 'INICIANTE',
    tags: [
      'quadril',
      'pelve',
      'quadril_pelve',
      'funcional',
      'step',
      'lateral',
      'baixo',
    ],
  },
  {
    nome: 'Avanco lateral assistido',
    slug: 'avanco-lateral-assistido',
    area: 'Quadril / pelve',
    regiaoCorporal: 'QUADRIL_PELVE',
    categoria: 'FUNCIONAL',
    nivel: 'INICIANTE',
    tags: [
      'quadril',
      'pelve',
      'quadril_pelve',
      'funcional',
      'avanco',
      'lateral',
      'assistido',
    ],
  },
  {
    nome: 'Mobilidade capsular quadril com faixa',
    slug: 'mobilidade-capsular-quadril-com-faixa',
    area: 'Quadril / pelve',
    regiaoCorporal: 'QUADRIL_PELVE',
    categoria: 'MOBILIDADE',
    nivel: 'INICIANTE',
    tags: [
      'quadril',
      'pelve',
      'quadril_pelve',
      'mobilidade',
      'capsular',
      'com',
      'faixa',
    ],
  },
  {
    nome: 'Controle pelvico em apoio unipodal',
    slug: 'controle-pelvico-em-apoio-unipodal',
    area: 'Quadril / pelve',
    regiaoCorporal: 'QUADRIL_PELVE',
    categoria: 'CONTROLE_MOTOR',
    nivel: 'INICIANTE',
    tags: [
      'quadril',
      'pelve',
      'quadril_pelve',
      'controle_motor',
      'controle',
      'pelvico',
      'apoio',
      'unipodal',
    ],
  },
  {
    nome: 'Caminhada retrograda com apoio',
    slug: 'caminhada-retrograda-com-apoio',
    area: 'Quadril / pelve',
    regiaoCorporal: 'QUADRIL_PELVE',
    categoria: 'FUNCIONAL',
    nivel: 'INICIANTE',
    tags: [
      'quadril',
      'pelve',
      'quadril_pelve',
      'funcional',
      'caminhada',
      'retrograda',
      'com',
      'apoio',
    ],
  },
  {
    nome: 'Isometria quadriceps sentado',
    slug: 'isometria-quadriceps-sentado',
    area: 'Joelho',
    regiaoCorporal: 'JOELHO',
    categoria: 'FORTALECIMENTO',
    nivel: 'INICIANTE',
    tags: ['joelho', 'fortalecimento', 'isometria', 'quadriceps', 'sentado'],
  },
  {
    nome: 'Extensao terminal joelho sem faixa',
    slug: 'extensao-terminal-joelho-sem-faixa',
    area: 'Joelho',
    regiaoCorporal: 'JOELHO',
    categoria: 'FORTALECIMENTO',
    nivel: 'INICIANTE',
    tags: ['joelho', 'fortalecimento', 'extensao', 'terminal', 'sem', 'faixa'],
  },
  {
    nome: 'Flexao joelho sentado com toalha',
    slug: 'flexao-joelho-sentado-com-toalha',
    area: 'Joelho',
    regiaoCorporal: 'JOELHO',
    categoria: 'MOBILIDADE',
    nivel: 'INICIANTE',
    tags: ['joelho', 'mobilidade', 'flexao', 'sentado', 'com', 'toalha'],
  },
  {
    nome: 'Deslizamento calcanhar sentado',
    slug: 'deslizamento-calcanhar-sentado',
    area: 'Joelho',
    regiaoCorporal: 'JOELHO',
    categoria: 'MOBILIDADE',
    nivel: 'INICIANTE',
    tags: ['joelho', 'mobilidade', 'deslizamento', 'calcanhar', 'sentado'],
  },
  {
    nome: 'Elevacao perna reta com rotacao externa',
    slug: 'elevacao-perna-reta-com-rotacao-externa',
    area: 'Joelho',
    regiaoCorporal: 'JOELHO',
    categoria: 'FORTALECIMENTO',
    nivel: 'INICIANTE',
    tags: [
      'joelho',
      'fortalecimento',
      'elevacao',
      'perna',
      'reta',
      'com',
      'rotacao',
      'externa',
    ],
  },
  {
    nome: 'Agachamento sentar tocar cadeira',
    slug: 'agachamento-sentar-tocar-cadeira',
    area: 'Joelho',
    regiaoCorporal: 'JOELHO',
    categoria: 'FUNCIONAL',
    nivel: 'INICIANTE',
    tags: ['joelho', 'funcional', 'agachamento', 'sentar', 'tocar', 'cadeira'],
  },
  {
    nome: 'Agachamento com bola na parede',
    slug: 'agachamento-com-bola-na-parede',
    area: 'Joelho',
    regiaoCorporal: 'JOELHO',
    categoria: 'FORTALECIMENTO',
    nivel: 'INICIANTE',
    tags: ['joelho', 'fortalecimento', 'agachamento', 'com', 'bola', 'parede'],
  },
  {
    nome: 'Step up lateral baixo',
    slug: 'step-up-lateral-baixo',
    area: 'Joelho',
    regiaoCorporal: 'JOELHO',
    categoria: 'FUNCIONAL',
    nivel: 'INICIANTE',
    tags: ['joelho', 'funcional', 'step', 'lateral', 'baixo'],
  },
  {
    nome: 'Step down lateral controlado',
    slug: 'step-down-lateral-controlado',
    area: 'Joelho',
    regiaoCorporal: 'JOELHO',
    categoria: 'FUNCIONAL',
    nivel: 'INICIANTE',
    tags: ['joelho', 'funcional', 'step', 'down', 'lateral', 'controlado'],
  },
  {
    nome: 'Mini avanco frontal',
    slug: 'mini-avanco-frontal',
    area: 'Joelho',
    regiaoCorporal: 'JOELHO',
    categoria: 'FUNCIONAL',
    nivel: 'INICIANTE',
    tags: ['joelho', 'funcional', 'mini', 'avanco', 'frontal'],
  },
  {
    nome: 'Mini avanco reverso',
    slug: 'mini-avanco-reverso',
    area: 'Joelho',
    regiaoCorporal: 'JOELHO',
    categoria: 'FUNCIONAL',
    nivel: 'INICIANTE',
    tags: ['joelho', 'funcional', 'mini', 'avanco', 'reverso'],
  },
  {
    nome: 'Ponte isquiotibiais com calcanhar',
    slug: 'ponte-isquiotibiais-com-calcanhar',
    area: 'Joelho',
    regiaoCorporal: 'JOELHO',
    categoria: 'FORTALECIMENTO',
    nivel: 'INICIANTE',
    tags: [
      'joelho',
      'fortalecimento',
      'ponte',
      'isquiotibiais',
      'com',
      'calcanhar',
    ],
  },
  {
    nome: 'Flexao joelho bola suica',
    slug: 'flexao-joelho-bola-suica',
    area: 'Joelho',
    regiaoCorporal: 'JOELHO',
    categoria: 'FORTALECIMENTO',
    nivel: 'INICIANTE',
    tags: ['joelho', 'fortalecimento', 'flexao', 'bola', 'suica'],
  },
  {
    nome: 'Cadeira extensora isometrica curta',
    slug: 'cadeira-extensora-isometrica-curta',
    area: 'Joelho',
    regiaoCorporal: 'JOELHO',
    categoria: 'FORTALECIMENTO',
    nivel: 'INICIANTE',
    tags: [
      'joelho',
      'fortalecimento',
      'cadeira',
      'extensora',
      'isometrica',
      'curta',
    ],
  },
  {
    nome: 'Wall sit curto',
    slug: 'wall-sit-curto',
    area: 'Joelho',
    regiaoCorporal: 'JOELHO',
    categoria: 'FORTALECIMENTO',
    nivel: 'INICIANTE',
    tags: ['joelho', 'fortalecimento', 'wall', 'sit', 'curto'],
  },
  {
    nome: 'Controle valgo com espelho',
    slug: 'controle-valgo-com-espelho',
    area: 'Joelho',
    regiaoCorporal: 'JOELHO',
    categoria: 'CONTROLE_MOTOR',
    nivel: 'INICIANTE',
    tags: ['joelho', 'controle_motor', 'controle', 'valgo', 'com', 'espelho'],
  },
  {
    nome: 'Aducao bola joelhos sentado',
    slug: 'aducao-bola-joelhos-sentado',
    area: 'Joelho',
    regiaoCorporal: 'JOELHO',
    categoria: 'FORTALECIMENTO',
    nivel: 'INICIANTE',
    tags: ['joelho', 'fortalecimento', 'aducao', 'bola', 'joelhos', 'sentado'],
  },
  {
    nome: 'Abducao joelhos sentado com faixa',
    slug: 'abducao-joelhos-sentado-com-faixa',
    area: 'Joelho',
    regiaoCorporal: 'JOELHO',
    categoria: 'FORTALECIMENTO',
    nivel: 'INICIANTE',
    tags: [
      'joelho',
      'fortalecimento',
      'abducao',
      'joelhos',
      'sentado',
      'com',
      'faixa',
    ],
  },
  {
    nome: 'Caminhada terminal joelho com faixa',
    slug: 'caminhada-terminal-joelho-com-faixa',
    area: 'Joelho',
    regiaoCorporal: 'JOELHO',
    categoria: 'CONTROLE_MOTOR',
    nivel: 'INICIANTE',
    tags: ['joelho', 'controle_motor', 'caminhada', 'terminal', 'com', 'faixa'],
  },
  {
    nome: 'Elevacao calcanhar unilateral com apoio',
    slug: 'elevacao-calcanhar-unilateral-com-apoio',
    area: 'Joelho',
    regiaoCorporal: 'JOELHO',
    categoria: 'FORTALECIMENTO',
    nivel: 'INICIANTE',
    tags: [
      'joelho',
      'fortalecimento',
      'elevacao',
      'calcanhar',
      'unilateral',
      'com',
      'apoio',
    ],
  },
  {
    nome: 'Mobilidade patelar autoassistida',
    slug: 'mobilidade-patelar-autoassistida',
    area: 'Joelho',
    regiaoCorporal: 'JOELHO',
    categoria: 'MOBILIDADE',
    nivel: 'INICIANTE',
    tags: ['joelho', 'mobilidade', 'patelar', 'autoassistida'],
  },
  {
    nome: 'Alongamento quadriceps em decubito lateral',
    slug: 'alongamento-quadriceps-em-decubito-lateral',
    area: 'Joelho',
    regiaoCorporal: 'JOELHO',
    categoria: 'MOBILIDADE',
    nivel: 'INICIANTE',
    tags: [
      'joelho',
      'mobilidade',
      'alongamento',
      'quadriceps',
      'decubito',
      'lateral',
    ],
  },
  {
    nome: 'Alongamento isquiotibiais sentado',
    slug: 'alongamento-isquiotibiais-sentado',
    area: 'Joelho',
    regiaoCorporal: 'JOELHO',
    categoria: 'MOBILIDADE',
    nivel: 'INICIANTE',
    tags: ['joelho', 'mobilidade', 'alongamento', 'isquiotibiais', 'sentado'],
  },
  {
    nome: 'Alongamento banda iliotibial em pe',
    slug: 'alongamento-banda-iliotibial-em-pe',
    area: 'Joelho',
    regiaoCorporal: 'JOELHO',
    categoria: 'MOBILIDADE',
    nivel: 'INICIANTE',
    tags: ['joelho', 'mobilidade', 'alongamento', 'banda', 'iliotibial'],
  },
  {
    nome: 'Mini agachamento unipodal com apoio',
    slug: 'mini-agachamento-unipodal-com-apoio',
    area: 'Joelho',
    regiaoCorporal: 'JOELHO',
    categoria: 'CONTROLE_MOTOR',
    nivel: 'INICIANTE',
    tags: [
      'joelho',
      'controle_motor',
      'mini',
      'agachamento',
      'unipodal',
      'com',
      'apoio',
    ],
  },
  {
    nome: 'Agachamento split assistido',
    slug: 'agachamento-split-assistido',
    area: 'Joelho',
    regiaoCorporal: 'JOELHO',
    categoria: 'FUNCIONAL',
    nivel: 'INICIANTE',
    tags: ['joelho', 'funcional', 'agachamento', 'split', 'assistido'],
  },
  {
    nome: 'Levantamento terra romeno unilateral apoio',
    slug: 'levantamento-terra-romeno-unilateral-apoio',
    area: 'Joelho',
    regiaoCorporal: 'JOELHO',
    categoria: 'FORTALECIMENTO',
    nivel: 'INICIANTE',
    tags: [
      'joelho',
      'fortalecimento',
      'levantamento',
      'terra',
      'romeno',
      'unilateral',
      'apoio',
    ],
  },
  {
    nome: 'Descida de escada simulada com apoio',
    slug: 'descida-de-escada-simulada-com-apoio',
    area: 'Joelho',
    regiaoCorporal: 'JOELHO',
    categoria: 'FUNCIONAL',
    nivel: 'INICIANTE',
    tags: [
      'joelho',
      'funcional',
      'descida',
      'escada',
      'simulada',
      'com',
      'apoio',
    ],
  },
  {
    nome: 'Dorsiflexao parede joelho a parede',
    slug: 'dorsiflexao-parede-joelho-a-parede',
    area: 'Tornozelo / pe',
    regiaoCorporal: 'TORNOZELO_PE',
    categoria: 'MOBILIDADE',
    nivel: 'INICIANTE',
    tags: [
      'tornozelo',
      'tornozelo_pe',
      'mobilidade',
      'dorsiflexao',
      'parede',
      'joelho',
    ],
  },
  {
    nome: 'Mobilidade tornozelo com faixa posterior',
    slug: 'mobilidade-tornozelo-com-faixa-posterior',
    area: 'Tornozelo / pe',
    regiaoCorporal: 'TORNOZELO_PE',
    categoria: 'MOBILIDADE',
    nivel: 'INICIANTE',
    tags: [
      'tornozelo',
      'tornozelo_pe',
      'mobilidade',
      'com',
      'faixa',
      'posterior',
    ],
  },
  {
    nome: 'Alongamento soleo parede',
    slug: 'alongamento-soleo-parede',
    area: 'Tornozelo / pe',
    regiaoCorporal: 'TORNOZELO_PE',
    categoria: 'MOBILIDADE',
    nivel: 'INICIANTE',
    tags: [
      'tornozelo',
      'tornozelo_pe',
      'mobilidade',
      'alongamento',
      'soleo',
      'parede',
    ],
  },
  {
    nome: 'Alongamento gastrocnemio no degrau',
    slug: 'alongamento-gastrocnemio-no-degrau',
    area: 'Tornozelo / pe',
    regiaoCorporal: 'TORNOZELO_PE',
    categoria: 'MOBILIDADE',
    nivel: 'INICIANTE',
    tags: [
      'tornozelo',
      'tornozelo_pe',
      'mobilidade',
      'alongamento',
      'gastrocnemio',
      'degrau',
    ],
  },
  {
    nome: 'Eversao tornozelo ativa sem faixa',
    slug: 'eversao-tornozelo-ativa-sem-faixa',
    area: 'Tornozelo / pe',
    regiaoCorporal: 'TORNOZELO_PE',
    categoria: 'MOBILIDADE',
    nivel: 'INICIANTE',
    tags: [
      'tornozelo',
      'tornozelo_pe',
      'mobilidade',
      'eversao',
      'ativa',
      'sem',
      'faixa',
    ],
  },
  {
    nome: 'Inversao tornozelo ativa sem faixa',
    slug: 'inversao-tornozelo-ativa-sem-faixa',
    area: 'Tornozelo / pe',
    regiaoCorporal: 'TORNOZELO_PE',
    categoria: 'MOBILIDADE',
    nivel: 'INICIANTE',
    tags: [
      'tornozelo',
      'tornozelo_pe',
      'mobilidade',
      'inversao',
      'ativa',
      'sem',
      'faixa',
    ],
  },
  {
    nome: 'Alfabeto tornozelo',
    slug: 'alfabeto-tornozelo',
    area: 'Tornozelo / pe',
    regiaoCorporal: 'TORNOZELO_PE',
    categoria: 'MOBILIDADE',
    nivel: 'INICIANTE',
    tags: ['tornozelo', 'tornozelo_pe', 'mobilidade', 'alfabeto'],
  },
  {
    nome: 'Flexao extensao dedos do pe',
    slug: 'flexao-extensao-dedos-do-pe',
    area: 'Tornozelo / pe',
    regiaoCorporal: 'TORNOZELO_PE',
    categoria: 'MOBILIDADE',
    nivel: 'INICIANTE',
    tags: [
      'tornozelo',
      'tornozelo_pe',
      'mobilidade',
      'flexao',
      'extensao',
      'dedos',
    ],
  },
  {
    nome: 'Abducao dedos do pe',
    slug: 'abducao-dedos-do-pe',
    area: 'Tornozelo / pe',
    regiaoCorporal: 'TORNOZELO_PE',
    categoria: 'CONTROLE_MOTOR',
    nivel: 'INICIANTE',
    tags: ['tornozelo', 'tornozelo_pe', 'controle_motor', 'abducao', 'dedos'],
  },
  {
    nome: 'Elevacao isolada do hallux',
    slug: 'elevacao-isolada-do-hallux',
    area: 'Tornozelo / pe',
    regiaoCorporal: 'TORNOZELO_PE',
    categoria: 'CONTROLE_MOTOR',
    nivel: 'INICIANTE',
    tags: [
      'tornozelo',
      'tornozelo_pe',
      'controle_motor',
      'elevacao',
      'isolada',
      'hallux',
    ],
  },
  {
    nome: 'Elevacao dedos menores isolada',
    slug: 'elevacao-dedos-menores-isolada',
    area: 'Tornozelo / pe',
    regiaoCorporal: 'TORNOZELO_PE',
    categoria: 'CONTROLE_MOTOR',
    nivel: 'INICIANTE',
    tags: [
      'tornozelo',
      'tornozelo_pe',
      'controle_motor',
      'elevacao',
      'dedos',
      'menores',
      'isolada',
    ],
  },
  {
    nome: 'Doming foot sentado',
    slug: 'doming-foot-sentado',
    area: 'Tornozelo / pe',
    regiaoCorporal: 'TORNOZELO_PE',
    categoria: 'CONTROLE_MOTOR',
    nivel: 'INICIANTE',
    tags: [
      'tornozelo',
      'tornozelo_pe',
      'controle_motor',
      'doming',
      'foot',
      'sentado',
    ],
  },
  {
    nome: 'Doming foot em pe',
    slug: 'doming-foot-em-pe',
    area: 'Tornozelo / pe',
    regiaoCorporal: 'TORNOZELO_PE',
    categoria: 'CONTROLE_MOTOR',
    nivel: 'INICIANTE',
    tags: ['tornozelo', 'tornozelo_pe', 'controle_motor', 'doming', 'foot'],
  },
  {
    nome: 'Pronacao supinacao pe sentado',
    slug: 'pronacao-supinacao-pe-sentado',
    area: 'Tornozelo / pe',
    regiaoCorporal: 'TORNOZELO_PE',
    categoria: 'CONTROLE_MOTOR',
    nivel: 'INICIANTE',
    tags: [
      'tornozelo',
      'tornozelo_pe',
      'controle_motor',
      'pronacao',
      'supinacao',
      'sentado',
    ],
  },
  {
    nome: 'Elevacao panturrilha unilateral apoio',
    slug: 'elevacao-panturrilha-unilateral-apoio',
    area: 'Tornozelo / pe',
    regiaoCorporal: 'TORNOZELO_PE',
    categoria: 'FORTALECIMENTO',
    nivel: 'INICIANTE',
    tags: [
      'tornozelo',
      'tornozelo_pe',
      'fortalecimento',
      'elevacao',
      'panturrilha',
      'unilateral',
      'apoio',
    ],
  },
  {
    nome: 'Elevacao tibial na parede',
    slug: 'elevacao-tibial-na-parede',
    area: 'Tornozelo / pe',
    regiaoCorporal: 'TORNOZELO_PE',
    categoria: 'FORTALECIMENTO',
    nivel: 'INICIANTE',
    tags: [
      'tornozelo',
      'tornozelo_pe',
      'fortalecimento',
      'elevacao',
      'tibial',
      'parede',
    ],
  },
  {
    nome: 'Caminhada lateral ponta dos pes',
    slug: 'caminhada-lateral-ponta-dos-pes',
    area: 'Tornozelo / pe',
    regiaoCorporal: 'TORNOZELO_PE',
    categoria: 'FUNCIONAL',
    nivel: 'INICIANTE',
    tags: [
      'tornozelo',
      'tornozelo_pe',
      'funcional',
      'caminhada',
      'lateral',
      'ponta',
      'dos',
      'pes',
    ],
  },
  {
    nome: 'Balance board frente tras',
    slug: 'balance-board-frente-tras',
    area: 'Tornozelo / pe',
    regiaoCorporal: 'TORNOZELO_PE',
    categoria: 'PROPRIOCEPCAO',
    nivel: 'INICIANTE',
    tags: [
      'tornozelo',
      'tornozelo_pe',
      'propriocepcao',
      'balance',
      'board',
      'frente',
      'tras',
    ],
  },
  {
    nome: 'Balance board lateral',
    slug: 'balance-board-lateral',
    area: 'Tornozelo / pe',
    regiaoCorporal: 'TORNOZELO_PE',
    categoria: 'PROPRIOCEPCAO',
    nivel: 'INICIANTE',
    tags: [
      'tornozelo',
      'tornozelo_pe',
      'propriocepcao',
      'balance',
      'board',
      'lateral',
    ],
  },
  {
    nome: 'Apoio unipodal olhos abertos',
    slug: 'apoio-unipodal-olhos-abertos',
    area: 'Tornozelo / pe',
    regiaoCorporal: 'TORNOZELO_PE',
    categoria: 'PROPRIOCEPCAO',
    nivel: 'INICIANTE',
    tags: [
      'tornozelo',
      'tornozelo_pe',
      'propriocepcao',
      'apoio',
      'unipodal',
      'olhos',
      'abertos',
    ],
  },
  {
    nome: 'Apoio unipodal alcance anterior',
    slug: 'apoio-unipodal-alcance-anterior',
    area: 'Tornozelo / pe',
    regiaoCorporal: 'TORNOZELO_PE',
    categoria: 'PROPRIOCEPCAO',
    nivel: 'INICIANTE',
    tags: [
      'tornozelo',
      'tornozelo_pe',
      'propriocepcao',
      'apoio',
      'unipodal',
      'alcance',
      'anterior',
    ],
  },
  {
    nome: 'Pogo hops baixos',
    slug: 'pogo-hops-baixos',
    area: 'Tornozelo / pe',
    regiaoCorporal: 'TORNOZELO_PE',
    categoria: 'PLIOMETRIA',
    nivel: 'INICIANTE',
    tags: ['tornozelo', 'tornozelo_pe', 'pliometria', 'pogo', 'hops', 'baixos'],
  },
  {
    nome: 'Step tornozelo controle descida',
    slug: 'step-tornozelo-controle-descida',
    area: 'Tornozelo / pe',
    regiaoCorporal: 'TORNOZELO_PE',
    categoria: 'FUNCIONAL',
    nivel: 'INICIANTE',
    tags: [
      'tornozelo',
      'tornozelo_pe',
      'funcional',
      'step',
      'controle',
      'descida',
    ],
  },
  {
    nome: 'Rolamento plantar com bola',
    slug: 'rolamento-plantar-com-bola',
    area: 'Tornozelo / pe',
    regiaoCorporal: 'TORNOZELO_PE',
    categoria: 'MOBILIDADE',
    nivel: 'INICIANTE',
    tags: [
      'tornozelo',
      'tornozelo_pe',
      'mobilidade',
      'rolamento',
      'plantar',
      'com',
      'bola',
    ],
  },
  {
    nome: 'Alongamento fascia plantar sentado',
    slug: 'alongamento-fascia-plantar-sentado',
    area: 'Tornozelo / pe',
    regiaoCorporal: 'TORNOZELO_PE',
    categoria: 'MOBILIDADE',
    nivel: 'INICIANTE',
    tags: [
      'tornozelo',
      'tornozelo_pe',
      'mobilidade',
      'alongamento',
      'fascia',
      'plantar',
      'sentado',
    ],
  },
  {
    nome: 'Marcha calcanhar ponta alternada',
    slug: 'marcha-calcanhar-ponta-alternada',
    area: 'Tornozelo / pe',
    regiaoCorporal: 'TORNOZELO_PE',
    categoria: 'FUNCIONAL',
    nivel: 'INICIANTE',
    tags: [
      'tornozelo',
      'tornozelo_pe',
      'funcional',
      'marcha',
      'calcanhar',
      'ponta',
      'alternada',
    ],
  },
  {
    nome: 'Sentar levantar com apoio unilateral',
    slug: 'sentar-levantar-com-apoio-unilateral',
    area: 'Equilibrio / marcha / quedas',
    regiaoCorporal: 'EQUILIBRIO_MARCHA',
    categoria: 'FUNCIONAL',
    nivel: 'INICIANTE',
    tags: [
      'equilibrio',
      'marcha',
      'equilibrio_marcha',
      'funcional',
      'sentar',
      'levantar',
      'com',
      'apoio',
      'unilateral',
    ],
  },
  {
    nome: 'Transferencia de peso diagonal',
    slug: 'transferencia-de-peso-diagonal',
    area: 'Equilibrio / marcha / quedas',
    regiaoCorporal: 'EQUILIBRIO_MARCHA',
    categoria: 'PROPRIOCEPCAO',
    nivel: 'INICIANTE',
    tags: [
      'equilibrio',
      'marcha',
      'equilibrio_marcha',
      'propriocepcao',
      'transferencia',
      'peso',
      'diagonal',
    ],
  },
  {
    nome: 'Alcance funcional anterior',
    slug: 'alcance-funcional-anterior',
    area: 'Equilibrio / marcha / quedas',
    regiaoCorporal: 'EQUILIBRIO_MARCHA',
    categoria: 'PROPRIOCEPCAO',
    nivel: 'INICIANTE',
    tags: [
      'equilibrio',
      'marcha',
      'equilibrio_marcha',
      'propriocepcao',
      'alcance',
      'funcional',
      'anterior',
    ],
  },
  {
    nome: 'Alcance lateral em pe',
    slug: 'alcance-lateral-em-pe',
    area: 'Equilibrio / marcha / quedas',
    regiaoCorporal: 'EQUILIBRIO_MARCHA',
    categoria: 'PROPRIOCEPCAO',
    nivel: 'INICIANTE',
    tags: [
      'equilibrio',
      'marcha',
      'equilibrio_marcha',
      'propriocepcao',
      'alcance',
      'lateral',
    ],
  },
  {
    nome: 'Marcha tandem com apoio',
    slug: 'marcha-tandem-com-apoio',
    area: 'Equilibrio / marcha / quedas',
    regiaoCorporal: 'EQUILIBRIO_MARCHA',
    categoria: 'PROPRIOCEPCAO',
    nivel: 'INICIANTE',
    tags: [
      'equilibrio',
      'marcha',
      'equilibrio_marcha',
      'propriocepcao',
      'tandem',
      'com',
      'apoio',
    ],
  },
  {
    nome: 'Marcha lateral com apoio',
    slug: 'marcha-lateral-com-apoio',
    area: 'Equilibrio / marcha / quedas',
    regiaoCorporal: 'EQUILIBRIO_MARCHA',
    categoria: 'FUNCIONAL',
    nivel: 'INICIANTE',
    tags: [
      'equilibrio',
      'marcha',
      'equilibrio_marcha',
      'funcional',
      'lateral',
      'com',
      'apoio',
    ],
  },
  {
    nome: 'Marcha retrograda com apoio',
    slug: 'marcha-retrograda-com-apoio',
    area: 'Equilibrio / marcha / quedas',
    regiaoCorporal: 'EQUILIBRIO_MARCHA',
    categoria: 'FUNCIONAL',
    nivel: 'INICIANTE',
    tags: [
      'equilibrio',
      'marcha',
      'equilibrio_marcha',
      'funcional',
      'retrograda',
      'com',
      'apoio',
    ],
  },
  {
    nome: 'Contornar cones com apoio',
    slug: 'contornar-cones-com-apoio',
    area: 'Equilibrio / marcha / quedas',
    regiaoCorporal: 'EQUILIBRIO_MARCHA',
    categoria: 'FUNCIONAL',
    nivel: 'INICIANTE',
    tags: [
      'equilibrio',
      'marcha',
      'equilibrio_marcha',
      'funcional',
      'contornar',
      'cones',
      'com',
      'apoio',
    ],
  },
  {
    nome: 'Subir degrau com corrimao',
    slug: 'subir-degrau-com-corrimao',
    area: 'Equilibrio / marcha / quedas',
    regiaoCorporal: 'EQUILIBRIO_MARCHA',
    categoria: 'FUNCIONAL',
    nivel: 'INICIANTE',
    tags: [
      'equilibrio',
      'marcha',
      'equilibrio_marcha',
      'funcional',
      'subir',
      'degrau',
      'com',
      'corrimao',
    ],
  },
  {
    nome: 'Descer degrau com corrimao',
    slug: 'descer-degrau-com-corrimao',
    area: 'Equilibrio / marcha / quedas',
    regiaoCorporal: 'EQUILIBRIO_MARCHA',
    categoria: 'FUNCIONAL',
    nivel: 'INICIANTE',
    tags: [
      'equilibrio',
      'marcha',
      'equilibrio_marcha',
      'funcional',
      'descer',
      'degrau',
      'com',
      'corrimao',
    ],
  },
  {
    nome: 'Treino de virada cento e oitenta graus',
    slug: 'treino-de-virada-cento-e-oitenta-graus',
    area: 'Equilibrio / marcha / quedas',
    regiaoCorporal: 'EQUILIBRIO_MARCHA',
    categoria: 'FUNCIONAL',
    nivel: 'INICIANTE',
    tags: [
      'equilibrio',
      'marcha',
      'equilibrio_marcha',
      'funcional',
      'treino',
      'virada',
      'cento',
      'oitenta',
      'graus',
    ],
  },
  {
    nome: 'Passada sobre obstaculo baixo',
    slug: 'passada-sobre-obstaculo-baixo',
    area: 'Equilibrio / marcha / quedas',
    regiaoCorporal: 'EQUILIBRIO_MARCHA',
    categoria: 'FUNCIONAL',
    nivel: 'INICIANTE',
    tags: [
      'equilibrio',
      'marcha',
      'equilibrio_marcha',
      'funcional',
      'passada',
      'sobre',
      'obstaculo',
      'baixo',
    ],
  },
  {
    nome: 'Dupla tarefa marcha simples',
    slug: 'dupla-tarefa-marcha-simples',
    area: 'Equilibrio / marcha / quedas',
    regiaoCorporal: 'EQUILIBRIO_MARCHA',
    categoria: 'FUNCIONAL',
    nivel: 'INICIANTE',
    tags: [
      'equilibrio',
      'marcha',
      'equilibrio_marcha',
      'funcional',
      'dupla',
      'tarefa',
      'simples',
    ],
  },
  {
    nome: 'Equilibrio semi tandem',
    slug: 'equilibrio-semi-tandem',
    area: 'Equilibrio / marcha / quedas',
    regiaoCorporal: 'EQUILIBRIO_MARCHA',
    categoria: 'PROPRIOCEPCAO',
    nivel: 'INICIANTE',
    tags: [
      'equilibrio',
      'marcha',
      'equilibrio_marcha',
      'propriocepcao',
      'semi',
      'tandem',
    ],
  },
  {
    nome: 'Equilibrio base estreita',
    slug: 'equilibrio-base-estreita',
    area: 'Equilibrio / marcha / quedas',
    regiaoCorporal: 'EQUILIBRIO_MARCHA',
    categoria: 'PROPRIOCEPCAO',
    nivel: 'INICIANTE',
    tags: [
      'equilibrio',
      'marcha',
      'equilibrio_marcha',
      'propriocepcao',
      'base',
      'estreita',
    ],
  },
  {
    nome: 'Reacao de passo anterior',
    slug: 'reacao-de-passo-anterior',
    area: 'Equilibrio / marcha / quedas',
    regiaoCorporal: 'EQUILIBRIO_MARCHA',
    categoria: 'PROPRIOCEPCAO',
    nivel: 'INICIANTE',
    tags: [
      'equilibrio',
      'marcha',
      'equilibrio_marcha',
      'propriocepcao',
      'reacao',
      'passo',
      'anterior',
    ],
  },
  {
    nome: 'Reacao de passo lateral',
    slug: 'reacao-de-passo-lateral',
    area: 'Equilibrio / marcha / quedas',
    regiaoCorporal: 'EQUILIBRIO_MARCHA',
    categoria: 'PROPRIOCEPCAO',
    nivel: 'INICIANTE',
    tags: [
      'equilibrio',
      'marcha',
      'equilibrio_marcha',
      'propriocepcao',
      'reacao',
      'passo',
      'lateral',
    ],
  },
  {
    nome: 'Treino levantar do chao assistido',
    slug: 'treino-levantar-do-chao-assistido',
    area: 'Equilibrio / marcha / quedas',
    regiaoCorporal: 'EQUILIBRIO_MARCHA',
    categoria: 'FUNCIONAL',
    nivel: 'INICIANTE',
    tags: [
      'equilibrio',
      'marcha',
      'equilibrio_marcha',
      'funcional',
      'treino',
      'levantar',
      'chao',
      'assistido',
    ],
  },
  {
    nome: 'Respiracao diafragmatica sentada',
    slug: 'respiracao-diafragmatica-sentada',
    area: 'Respiracao / relaxamento / neuro leve',
    regiaoCorporal: 'RESPIRATORIO_NEURO',
    categoria: 'CONTROLE_MOTOR',
    nivel: 'INICIANTE',
    tags: [
      'respiracao',
      'neuro',
      'respiratorio_neuro',
      'controle_motor',
      'diafragmatica',
      'sentada',
    ],
  },
  {
    nome: 'Respiracao com labios semicerrados',
    slug: 'respiracao-com-labios-semicerrados',
    area: 'Respiracao / relaxamento / neuro leve',
    regiaoCorporal: 'RESPIRATORIO_NEURO',
    categoria: 'CONTROLE_MOTOR',
    nivel: 'INICIANTE',
    tags: [
      'respiracao',
      'neuro',
      'respiratorio_neuro',
      'controle_motor',
      'com',
      'labios',
      'semicerrados',
    ],
  },
  {
    nome: 'Expansao toracica com bracos',
    slug: 'expansao-toracica-com-bracos',
    area: 'Respiracao / relaxamento / neuro leve',
    regiaoCorporal: 'RESPIRATORIO_NEURO',
    categoria: 'MOBILIDADE',
    nivel: 'INICIANTE',
    tags: [
      'respiracao',
      'neuro',
      'respiratorio_neuro',
      'mobilidade',
      'expansao',
      'toracica',
      'com',
      'bracos',
    ],
  },
  {
    nome: 'Relaxamento progressivo de ombros',
    slug: 'relaxamento-progressivo-de-ombros',
    area: 'Respiracao / relaxamento / neuro leve',
    regiaoCorporal: 'RESPIRATORIO_NEURO',
    categoria: 'CONTROLE_MOTOR',
    nivel: 'INICIANTE',
    tags: [
      'respiracao',
      'neuro',
      'respiratorio_neuro',
      'controle_motor',
      'relaxamento',
      'progressivo',
      'ombros',
    ],
  },
  {
    nome: 'Mobilidade global sentado',
    slug: 'mobilidade-global-sentado',
    area: 'Respiracao / relaxamento / neuro leve',
    regiaoCorporal: 'RESPIRATORIO_NEURO',
    categoria: 'MOBILIDADE',
    nivel: 'INICIANTE',
    tags: [
      'respiracao',
      'neuro',
      'respiratorio_neuro',
      'mobilidade',
      'global',
      'sentado',
    ],
  },
  {
    nome: 'Abertura fechamento maos bilateral',
    slug: 'abertura-fechamento-maos-bilateral',
    area: 'Respiracao / relaxamento / neuro leve',
    regiaoCorporal: 'RESPIRATORIO_NEURO',
    categoria: 'CONTROLE_MOTOR',
    nivel: 'INICIANTE',
    tags: [
      'respiracao',
      'neuro',
      'respiratorio_neuro',
      'controle_motor',
      'abertura',
      'fechamento',
      'maos',
      'bilateral',
    ],
  },
  {
    nome: 'Alcance cruzado sentado',
    slug: 'alcance-cruzado-sentado',
    area: 'Respiracao / relaxamento / neuro leve',
    regiaoCorporal: 'RESPIRATORIO_NEURO',
    categoria: 'CONTROLE_MOTOR',
    nivel: 'INICIANTE',
    tags: [
      'respiracao',
      'neuro',
      'respiratorio_neuro',
      'controle_motor',
      'alcance',
      'cruzado',
      'sentado',
    ],
  },
  {
    nome: 'Marcha sentada com bracos alternados',
    slug: 'marcha-sentada-com-bracos-alternados',
    area: 'Respiracao / relaxamento / neuro leve',
    regiaoCorporal: 'RESPIRATORIO_NEURO',
    categoria: 'FUNCIONAL',
    nivel: 'INICIANTE',
    tags: [
      'respiracao',
      'neuro',
      'respiratorio_neuro',
      'funcional',
      'marcha',
      'sentada',
      'com',
      'bracos',
      'alternados',
    ],
  },
  {
    nome: 'Levantar ponta do pe alternado sentado',
    slug: 'levantar-ponta-do-pe-alternado-sentado',
    area: 'Respiracao / relaxamento / neuro leve',
    regiaoCorporal: 'RESPIRATORIO_NEURO',
    categoria: 'CONTROLE_MOTOR',
    nivel: 'INICIANTE',
    tags: [
      'respiracao',
      'neuro',
      'respiratorio_neuro',
      'controle_motor',
      'levantar',
      'ponta',
      'alternado',
      'sentado',
    ],
  },
  {
    nome: 'Coordenacao calcanhar joelho sentado',
    slug: 'coordenacao-calcanhar-joelho-sentado',
    area: 'Respiracao / relaxamento / neuro leve',
    regiaoCorporal: 'RESPIRATORIO_NEURO',
    categoria: 'CONTROLE_MOTOR',
    nivel: 'INICIANTE',
    tags: [
      'respiracao',
      'neuro',
      'respiratorio_neuro',
      'controle_motor',
      'coordenacao',
      'calcanhar',
      'joelho',
      'sentado',
    ],
  },
];

function buildObjective(item: MasterExerciseTemplate): string {
  return (
    'Preparar avaliacao clinica e prescricao futura de ' +
    item.nome.toLowerCase() +
    '.'
  );
}

function buildDescription(item: MasterExerciseTemplate): string {
  return (
    'Exercicio do catalogo mestre Synap para ' +
    item.area.toLowerCase() +
    ': ' +
    item.nome.toLowerCase() +
    '.'
  );
}

function buildInstructions(item: MasterExerciseTemplate): string {
  return [
    '1. Confirmar indicacao clinica, nivel de irritabilidade e necessidade de supervisao antes de prescrever.',
    '2. Executar ' +
      item.nome.toLowerCase() +
      ' em baixa intensidade, com amplitude confortavel e velocidade controlada.',
    '3. Priorizar alinhamento, respiracao calma, apoio seguro e ausencia de compensacoes bruscas.',
    '4. Interromper se houver tontura, formigamento novo, perda de forca, instabilidade ou piora de sintomas que persista por 24h.',
  ].join('\n');
}

function buildCare(item: MasterExerciseTemplate): string {
  return (
    'Rascunho de catalogo mestre. Revisar clinicamente objetivo, indicacao, contraindicacoes, progressao, regressao e imagem antes de liberar ' +
    item.nome.toLowerCase() +
    ' para prescricao.'
  );
}

export const MASTER_EXERCISE_CATALOG: MasterExerciseSeed[] =
  MASTER_EXERCISE_TEMPLATES.map((item) => ({
    nome: item.nome,
    slug: item.slug,
    regiaoCorporal: item.regiaoCorporal,
    categoria: item.categoria,
    nivel: item.nivel,
    objetivo: buildObjective(item),
    descricao: buildDescription(item),
    instrucoesPadrao: buildInstructions(item),
    cuidados: buildCare(item),
    contraindicacoes:
      'Nao liberar para prescricao sem revisao clinica, imagem propria e aprovacao do exercicio. Evitar em dor aguda intensa, instabilidade importante, tontura, queda recente nao avaliada ou sintomas neurologicos progressivos.',
    imagemKey: null,
    tags: item.tags,
    status: ExercicioStatus.RASCUNHO,
  }));
